### ISSUE TITLE
How to make racer work with YouCompleteMe?

### ISSUE THREAD

**Issue by amosbird** [phildawes/racer#100]
I use the provided racer.vim and it fails to make semantic completion with youcompleteme.

**Comment by phildawes** [comment]
I don't know much about vim. Is this just that it hasn't been written to work with these, or is there a bug that prevents interoperability or something?

Any patches would be gratefully accepted!

**Comment by amosbird** [comment]
I‘ve opened an issue on Youcompleteme. It seems the author of YCM will soon start working on this.

**Comment by tomjakubowski** [comment]
For reference: Valloric/YouCompleteMe#1297
