### ISSUE TITLE
Compilation error on latest Rust version

### ISSUE THREAD

**Issue by jaxx** [phildawes/racer#104]
Hi,

I'm getting the following error when compiling using latest rustc.

```
C:\Rust\racer>rustc -O -o bin/racer src/main.rs
src\racer\codeiter.rs:22:10: 22:32 error: wrong number of type arguments: expected 0, found 1
src\racer\codeiter.rs:22 impl<'a> Iterator<(uint, uint)> for StmtIndicesIter<'a> {
```

**Comment by ChrisJan00** [comment]
I just pulled this project and found the same problem when building.  I managed to get it working, but I'm a total noob with rust, just starting to learn now.

In codeiter.rs, starting at line 22, change Iterator declaration and insert "type Item" declaration:
```
impl<'a> Iterator for StmtIndicesIter<'a> {
    type Item = (uint, uint);
    #[inline]
    fn next(&mut self) -> Option<(uint, uint)> {
```
In  codecleaner.rs, starting at line 38, same changes:
```
impl<'a> Iterator for CodeIndicesIter<'a> {
    type Item = (uint, uint);
    #[inline]
    fn next(&mut self) -> Option<(uint, uint)> {
```

In main.rs, add new attribute:
```
#![feature(associated_types)]
```

That did it for me, hope this helps.  
The latest racer commit I pulled is 389d84c. The versions of  rustc and cargo that I have: 
```
rustc 0.13.0-nightly (c6c786671 2015-01-04 00:50:59 +0000)
cargo 0.0.1-pre-nightly (4657875 2015-01-03 23:29:22 +0000)
```

**Comment by jaxx** [comment]
Problem solved with this merge, thanks!
