### ISSUE TITLE
Provide a completer to YCM

### ISSUE THREAD

**Issue by SirVer** [phildawes/racer#109]
Great work on racer! This will be super useful once it is more dynamic. 

https://github.com/Valloric/YouCompleteMe is a code completion plugin for Vim that is very sophisticated. It provides IDE like completion for C++ but integrates with other completers too. I use it for python, c++ and java and love it in all languages.

YCM has solved the UI problem in Vim completely, racer should be a completer for it in Vim, not a stand alone plugin.

**Comment by phildawes** [comment]
Hi SirVer,
Thanks man! I'm not a vim user but it seems a lot of people really like YouCompleteMe. 

Currently I'm spending all my limited coding time on the type inference aspect of racer - I'm kind of hoping that other people might pitch in for integration with various editors.
N.B. @valloric is a rust contributor and there's this https://github.com/Valloric/YouCompleteMe/issues/1297 so fingers crossed!

**Comment by Valloric** [comment]
I'll be integrating racer into ycmd some time in the near future.

@phildawes For the sake of speed, it would be excellent if racer were available as a library. The current approach requires calling the racer binary for each completion, which requires constant process setup/teardown. This is wasteful.

With a library API, there's yet more opportunity for perf gains. libclang for instance will build an AST of a C++ file and will return a TU object; completion requests can then provide the TU object and libclang will merely update the AST with file changes. This way most of the work is not thrown away. Massive perf gains arise out of this; the second, third etc libclang parse of a file is usually _many_ times faster than the first parse.

This kind of architecture is not possible if a racer process is constantly created and destroyed; a complete parse is necessary all the time.

But just avoiding process setup/teardown itself would be great, even if the API always did a clean parse. I'd love to see improvements along these lines in racer. 

Thoughts?

**Comment by Valloric** [comment]
Oh, another huge benefit of a library API is that tools that want to use racers info can skip the serialization/deserialization step. With the process approach, racer gets the completion data and then serializes it to stdout, and tools then need to parse that output back into their own data-structures. Avoiding this would be great.

**Comment by Valloric** [comment]
I see there's already #94 which tracks what the feature I requested.

**Comment by SirVer** [comment]
The internet is a tiny space really. Funny that we both developed an interest in Rust, @Valloric. What are you doing with the language? Maybe even at work?

@phildawes I agree with Val that racer should be a library first and an executable second - not only for editor integration, but it will make using it much easier and more pleasant for most tasks. Also, if Val is doing the YCM integration himself, it will be a super awesome experience to use :).

**Comment by Valloric** [comment]
> The internet is a tiny space really. Funny that we both developed an interest in Rust, @Valloric. What are you doing with the language? Maybe even at work?

I'm guessing you do C++ dev as well, which would naturally mean you'd prefer to write Rust instead for the same use-cases. :D

Not using it at work (you know how it is), just personal stuff.

**Comment by phildawes** [comment]
Hi @Valloric + @SirVer! 
Thanks for the input, if I get a chance I'll split out a separate library some time this week. Racer currently only parses enough of the ast to perform the query rather than a full parse of each file (and it modifies the pieces of code to make them faster to parse - e.g. an empty function body if it only needs the return type). There might be some benefit to caching, but for the time being I'm planning to stick with a clean parse to keep things simple.
It looks like there are some moves afoot to make rust's compiler more incremental - if that happens then that might change things substantially.
Cheers! Phil

**Comment by dirvine** [comment]
Has there been any move on this in YCM yet. It would be very cool for sure.

**Comment by phildawes** [comment]
Hi @dirvine
No move yet as far as I know. I am currently working on getting racer to work more closely with the rust compiler for type inference, which is a big job. As part of that I suspect racer will need to operate as a long lived process which is more inline with what @Valloric wants.

**Comment by wsdjeg** [comment]
does it support java complete

**Comment by ijks** [comment]
What's the progress on this currently?

**Comment by wsdjeg** [comment]
agree with @SirVer

but i think racer it self should be able to used without any other complete engin ，like javacomplete2 i am using,i can use javacomplete2 directly in vim ,also i can use neocomplete catch the source of javacomplete2 and provide a better fuzzy match,now with the help of neovim ,i am also able to use deoplete catch the source,the deoplete provide a completion from more than one source,for example,i can see the completion from tags buffers omni or any other you want at the same time!

**Comment by oblitum** [comment]
There's progress, it's ongoing.

For more information check https://github.com/jwilm/racerd by @jwilm.

**Comment by jwilm** [comment]
I've got a [work-in-progress PR](https://github.com/Valloric/ycmd/pull/268) up for ycmd (complete with demo gif). There are a couple of issues before that lands, but I am confident they will be resolved quickly. After that, we need to update YouCompleteMe (mostly just docs) to make it available for general use.

**Comment by phildawes** [comment]
This is awesome. nice work @jwilm

**Comment by jwilm** [comment]
This can be closed now :).

YCM PR that just got merged: https://github.com/Valloric/YouCompleteMe/pull/1888
reddit thread: https://www.reddit.com/r/rust/comments/404nno/youcompleteme_rust/
