### ISSUE TITLE
error: rustrt-4e7c5ce5c.dll is missing

### ISSUE THREAD

**Issue by hastebrot** [phildawes/racer#110]
Build https://github.com/phildawes/racer/commit/4c7297c on Windows 7 (64bit) using newest Rust nightly using `cargo build`. It throws the system error when running `bin\racer.exe`.

**Comment by hastebrot** [comment]
It run without errors using `rustc -O -o bin\racer src\main.rs`.

**Comment by phildawes** [comment]
Hi Hastebrot, Do you mean it now works?

**Comment by hastebrot** [comment]
It works with `rustc`. However it shows the system error when using `cargo build`.

**Comment by yacoder** [comment]
I've seen `cargo` crashing on Windows too, with the latest builds/sources, though not sure it was the same issue as the OP had, but everything seems to work if I run `cargo` from the msys2/mingw64 shell, as described on the Rust official page in the "Building on Windows" section: https://github.com/rust-lang/rust

**Comment by phildawes** [comment]
I'm closing this for now as an issue with rust/cargo. Please reopen if I've got this assessment wrong. Thanks
