### ISSUE TITLE
Where are the sources?

### ISSUE THREAD

**Issue by G4143** [phildawes/racer#111]
You say we have to set this environment variable here

RUST_SRC_PATH=/usr/local/src/rust/src

But I can't find any source files with my Rust 1.0.0 alpha install. I can find a bunch of .html files in /usr/local/share/doc/rust/html/src but that's it. Any help will be appreciated..

Running/trying this on a Mageia Linux box.

**Comment by ebfe** [comment]
The installer doesn't come with the source code. You can check it out from git https://github.com/rust-lang/rust or download it here http://www.rust-lang.org/install.html.

**Comment by G4143** [comment]
And now it works with Sublime. Thanks for pointing where to get the sources.
