### ISSUE TITLE
Not getting any autocomplete suggesstions

### ISSUE THREAD

**Issue by naveensrinivasan** [phildawes/racer#112]
I have the latest sourcecode and when I try doing the simple autocomplete it doesn't work.
`bin git:(master) ./racer complete std::io::B`

Any suggestions?

Thanks

**Comment by ebfe** [comment]
I can't reproduce this with current master (c0afd513).

Running `RUST_LOG=debug racer complete std::io::B` might provide more information on what is going wrong.

**Comment by naveensrinivasan** [comment]
Here is the output
➜ bin git:(master) RUST_LOG=debug ./racer complete std::io::B
DEBUG:main::racer::nameres: do_file_search std
DEBUG:main::racer::nameres: do_file_search srcpaths ~/rust/src/
DEBUG:main::racer::nameres: do_file_search v is ["~/rust/src/", "."]

**Comment by ebfe** [comment]
On Tue, Jan 13, 2015 at 06:12:06PM -0800, Naveen wrote:
> DEBUG:main::racer::nameres: do_file_search v is ["~/rust/src/", "."]

I think racer doesn't expand the '~'. Replacing '~' with your home
directory might help.

**Comment by naveensrinivasan** [comment]
Here is what I got

➜  bin git:(master) RUST_LOG=debug ./racer complete std::io:B
DEBUG:main::racer::nameres: do_file_search std
DEBUG:main::racer::nameres: do_file_search srcpaths /Users/naveen/rust/src/
DEBUG:main::racer::nameres: do_file_search v is ["/Users/naveen/rust/src/", "."]
DEBUG:main::racer::nameres: do_external_search path ["io:B"] Some("/Users/naveen/rust/src/libstd/lib.rs")
DEBUG:main::racer::nameres: searching scope BothNamespaces start: 0 point: 0 'io:B' Some("/Users/naveen/rust/src/libstd/lib.rs") StartsWith local: false
DEBUG:main::racer::nameres: search_scope found matches StartsWith []

**Comment by ebfe** [comment]
On Wed, Jan 14, 2015 at 03:16:53AM -0800, Naveen wrote:
> Here is what I got
> 
> ➜  bin git:(master) RUST_LOG=debug ./racer complete std::io:B

You are missing a colon after the `std::io`.

**Comment by naveensrinivasan** [comment]
Thanks. Got it!
