### ISSUE TITLE
strange error on osx

### ISSUE THREAD

**Issue by Fredmf** [phildawes/racer#118]
when i try to start racer i get this:

dyld: Symbol not found: __ZN3ast22Expr_...std..fmt..Show3fmt20h4c4ee2316f34ef64ojjE
  Referenced from: /usr/local/bin/racer
  Expected in: /usr/local/lib/libsyntax-4e7c5e5c.dylib
 in /usr/local/bin/racer
[1]    50911 trace trap  racer

i checked all paths, everything in place

i have no /usr/local/src folder, an i dont know where the sources for rust are, so i donwloaded the rust github project and set the path to the source folder there

**Comment by phildawes** [comment]
This is a link error as racer starts (rather than any logic in racer). My guess is that the libsyntax library in the error message isn't the same version as the version of rust that you built racer with. Does that make sense? Try re-installing rust, then build racer with the installed version.
