### ISSUE TITLE
Build error in racer v2.2.2

### ISSUE THREAD

**Issue by killme2008** [phildawes/racer#1181]
I ran command `cargo +nightly install racer` on mac, but it failed with an error as below:

```
36 |     fn fallback_fluent_bundle(&self) -> &Lrc<rustc_errors::FluentBundle> {
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                                         |
   |                                         expected struct `fluent_bundle::bundle::FluentBundle`, found struct `Lrc`
   |                                         help: change the output type to match the trait: `&fluent_bundle::bundle::FluentBundle<fluent_bundle::resource::FluentResource, intl_memoizer::IntlLangMemoizer>`
```

Some information may be useful:

```
➜  ~ rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

**Comment by calebcartwright** [comment]
First want to note that racer is [essentially end of life](https://github.com/racer-rust/racer#disclaimer) and users are encouraged to use alternatives like Rust Analyzer instead.

This is functionally a duplicate of similar issues, e.g. #1173, but if for some reason you still need to build racer then you need to use a supported nightly toolchain, not just any nightly toolchain.

The easiest way to identify a supported nightly toolchain is to look at the toolchain file in the repo:
https://github.com/racer-rust/racer/blob/a457c235b545c5251570cda8fec1edeab05ab1d4/rust-toolchain.toml#L2

**Comment by killme2008** [comment]
@calebcartwright  thank you, i will try it.
