### ISSUE TITLE
can't compile on nightly

### ISSUE THREAD

**Issue by ellisonch** [phildawes/racer#119]
I'm currently unable to compiler racer on nightly.  This is my first time trying to compile racer.

```
$ cargo build --release
   Compiling racer v0.0.1 (file:///D:/prog/racer)
src\racer\ast.rs:1026:23: 1031:10 error: non-exhaustive patterns: `DefaultReturn(_)` not covered [E0004]
src\racer\ast.rs:1026         self.result = match fd.output {
src\racer\ast.rs:1027             ast::Return(ref ty) =>
src\racer\ast.rs:1028                 to_racer_ty(&**ty, &self.scope),
src\racer\ast.rs:1029             ast::NoReturn(_) =>
src\racer\ast.rs:1030                 None,
src\racer\ast.rs:1031         };
error: aborting due to previous error
Could not compile `racer`.
```
on version
```
$ rustc --version
rustc 1.0.0-nightly (29bd9a06e 2015-01-20 23:03:09 +0000)
```

**Comment by phildawes** [comment]
Thanks Chucky, I'll try to get this fixed tonight. I think at the moment it
compiles with rust alpha

**Comment by D-Wagner** [comment]
I think that you should just be able to make the match exhaustive by adding `ast::DefaultReturn(_) => None,`.  I have it built, compiled and working (so far as I can tell) with that change.  DefaultReturn seems to behave just like NoReturn anyway.

**Comment by phildawes** [comment]
Oops, forgot to push the fix I did last night. Should be fixed now.
Thanks again
