### ISSUE TITLE
Build fails on Jan 28th (and later) builds

### ISSUE THREAD

**Issue by Shchvova** [phildawes/racer#126]
`rustc --version`
`rustc 1.0.0-nightly (c5961ad06 2015-01-28 21:49:38 +0000)`

`cargo build --release`
fails with error: 
```
src/racer/util.rs:81:13: 81:38 error: use of unmarked library feature
src/racer/util.rs:81 let s = std::rt::backtrace::write(&mut m)
```
replacing body `get_backtrace` with  `return "backtrace".to_string();` helps and autocomplete works, but it is hardly a solution.

**Comment by ebfe** [comment]
The underlying problem seems to be that std::rt::backtrace is missing a stability attribute. Commenting out get_backtrace in util.rs and the single call to it in nameres.rs:756 shouldn't have any ill effects, as it its only used for debug output.

**Comment by Shchvova** [comment]
Thanks. That is what I basically did :+1:
