### ISSUE TITLE
<command>-. doesn't jump to definitions on OS X

### ISSUE THREAD

**Issue by eklavya** [phildawes/racer#132]
Autocompletion is working fine but jump to definition is not. I did a reset of my emacs install to make sure there were no missing/bad configs. I am new to emacs so please tell me how I can supply more information to you if you need it.

**Comment by eklavya** [comment]
no love for me? :'(

**Comment by phildawes** [comment]
Hi Saurabh,
Are there any error messages when you press meta-.? Anything in *messages*
that might hint at what's going on?
Also check that the key binding is 'racer-find-definition'

Cheers,

Phil

**Comment by eklavya** [comment]
Hi,

I am so sorry, I am such a noob. It was supposed to be Meta+. I was doing Cmd+.

By the way, does racer pick up all sources from RUST_SRC_PATH? Any particular dir format (src/lib.rs)?
I was experimenting and got the full path from cargo but racer didn't seem to use it.

Apologies for changing the subject. I had also commented on the relevant issue.
