### ISSUE TITLE
Segfault on release build

### ISSUE THREAD

**Issue by yohanesu** [phildawes/racer#139]
System is Lubuntu 14.04 on 2013 Macbook Air. I just installed rust+racer and tried the test as it says in the install instructions.

./target/release/racer complete std:io segfaults

(gdb) r complete std::io
Starting program: /home/mirama/rust/racer/target/release/racer complete std::io
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6c7daca in old_io::buffered::LineBufferedWriter$LT$W$GT$.Writer::write_all::h4432282246901293695 () from /usr/local/lib/libstd-4e7c5e5c.so

However, if I build with
$ cargo build
and run with
./target/racer complete std::io
it works as expected.

**Comment by phildawes** [comment]
Hi @yohanesu 
Thanks for the report! Nuts,  that happens on my machine too! That sucks.
I'll look into this tonight.

**Comment by jgillich** [comment]
On my machine, the dev build doesn't segfault, but it doesn't output anything either (it should, right? source path is correct)

```
$ ./target/release/racer complete std::io::B
Illegal instruction (core dumped)
$ ./target/racer complete std::io::B
```
Latest nightly on Fedora.

**Comment by eklavya** [comment]
There is a whole bunch of mis-happenings with this. https://github.com/rust-lang/rust/issues/22008

**Comment by phildawes** [comment]
Hi @jgillich,
I get
```
$ ./target/racer complete std::io::B
MATCH BufReader,31,11,/usr/local/src/rust/src/libstd/io/buffered.rs,Struct,pub struct BufReader<R> {
MATCH BufWriter,115,11,/usr/local/src/rust/src/libstd/io/buffered.rs,Struct,pub struct BufWriter<W> {
MATCH BufStream,329,11,/usr/local/src/rust/src/libstd/io/buffered.rs,Struct,pub struct BufStream<S> {
MATCH BufRead,513,10,/usr/local/src/rust/src/libstd/io/mod.rs,Trait,pub trait BufRead: Read {
MATCH BufReadExt,582,10,/usr/local/src/rust/src/libstd/io/mod.rs,Trait,pub trait BufReadExt: BufRead + Sized {
MATCH Broadcast,614,11,/usr/local/src/rust/src/libstd/io/mod.rs,Struct,pub struct Broadcast<T, U> {
MATCH Bytes,701,11,/usr/local/src/rust/src/libstd/io/mod.rs,Struct,pub struct Bytes<R> {
```
Does your RUST_SRC_PATH include 'src'? - e.g. /usr/local/src/rust/src

**Comment by dariusc93** [comment]
@phildawes it happens in release mode. I, too, get such an error in release mode while on Ubuntu 14.04 and 14.10 (though I know its not OS related but possibly related to rust itself)

**Comment by phildawes** [comment]
Hi @dariusc93, I think it's os + rust related: people on osx seem to be ok. On ubuntu linux I too get the segfault on the release build but ok albeit slow on debug. (N.B. my reply to @jgillich was about the debug build, didn't make that clear sorry)
