### ISSUE TITLE
`cargo test` fails on latest rustc nightly (rustc 1.0.0-nightly (d3732a12e 2015-02-06 23:30:17 +0000))

### ISSUE THREAD

**Issue by fitzgen** [phildawes/racer#146]
$ cargo test
       Compiling racer v0.0.1 (file:///Users/fitzgen/src/racer)
    src/racer/scopes.rs:12:22: 12:30 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
    src/racer/scopes.rs:12 fn find_close<'a, A>(mut iter: A, open: u8, close: u8, level_end: u32) -> Option<usize>
                                                ^~~~~~~~
    src/racer/scopes.rs:117:42: 117:43 warning: unused variable: `i`, #[warn(unused_variables)] on by default
    src/racer/scopes.rs:117     match s.char_indices().rev().find(|&(i, c)| !util::is_ident_char(c)) {
                                                                     ^
    src/racer/nameres.rs:312:20: 312:35 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/nameres.rs:312     let srcpaths = std::os::getenv("RUST_SRC_PATH").unwrap_or("".to_string());
                                                ^~~~~~~~~~~~~~~
    src/racer/nameres.rs:487:20: 487:35 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/nameres.rs:487     let srcpaths = std::os::getenv("RUST_SRC_PATH").unwrap();
                                                ^~~~~~~~~~~~~~~
    src/racer/nameres.rs:761:26: 761:41 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/nameres.rs:761     let srcpaths = match std::os::getenv("RUST_SRC_PATH") { 
                                                      ^~~~~~~~~~~~~~~
    src/racer/bench.rs:1:1: 1:19 warning: use of unstable library feature 'test'
    src/racer/bench.rs:1 extern crate test;
                         ^~~~~~~~~~~~~~~~~~
    src/racer/bench.rs:1:1: 1:19 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:1 extern crate test;
                         ^~~~~~~~~~~~~~~~~~
    src/racer/bench.rs:25:7: 27:7 warning: use of unstable library feature 'test'
    src/racer/bench.rs:25     b.iter(|| {
    src/racer/bench.rs:26         test::black_box(code_chunks(src).collect::<Vec<_>>());
    src/racer/bench.rs:27     });
    src/racer/bench.rs:25:7: 27:7 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:25     b.iter(|| {
    src/racer/bench.rs:26         test::black_box(code_chunks(src).collect::<Vec<_>>());
    src/racer/bench.rs:27     });
    src/racer/bench.rs:26:9: 26:24 warning: use of unstable library feature 'test'
    src/racer/bench.rs:26         test::black_box(code_chunks(src).collect::<Vec<_>>());
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:26:9: 26:24 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:26         test::black_box(code_chunks(src).collect::<Vec<_>>());
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:33:7: 35:7 warning: use of unstable library feature 'test'
    src/racer/bench.rs:33     b.iter(|| {
    src/racer/bench.rs:34         test::black_box(iter_stmts(src).collect::<Vec<_>>());
    src/racer/bench.rs:35     });
    src/racer/bench.rs:33:7: 35:7 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:33     b.iter(|| {
    src/racer/bench.rs:34         test::black_box(iter_stmts(src).collect::<Vec<_>>());
    src/racer/bench.rs:35     });
    src/racer/bench.rs:34:9: 34:24 warning: use of unstable library feature 'test'
    src/racer/bench.rs:34         test::black_box(iter_stmts(src).collect::<Vec<_>>());
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:34:9: 34:24 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:34         test::black_box(iter_stmts(src).collect::<Vec<_>>());
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:41:7: 43:7 warning: use of unstable library feature 'test'
    src/racer/bench.rs:41     b.iter(|| {
    src/racer/bench.rs:42         test::black_box(mask_comments(src));
    src/racer/bench.rs:43     });
    src/racer/bench.rs:41:7: 43:7 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:41     b.iter(|| {
    src/racer/bench.rs:42         test::black_box(mask_comments(src));
    src/racer/bench.rs:43     });
    src/racer/bench.rs:42:9: 42:24 warning: use of unstable library feature 'test'
    src/racer/bench.rs:42         test::black_box(mask_comments(src));
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:42:9: 42:24 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:42         test::black_box(mask_comments(src));
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:49:7: 51:7 warning: use of unstable library feature 'test'
    src/racer/bench.rs:49     b.iter(|| {
    src/racer/bench.rs:50         test::black_box(mask_sub_scopes(src));
    src/racer/bench.rs:51     });
    src/racer/bench.rs:49:7: 51:7 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:49     b.iter(|| {
    src/racer/bench.rs:50         test::black_box(mask_sub_scopes(src));
    src/racer/bench.rs:51     });
    src/racer/bench.rs:50:9: 50:24 warning: use of unstable library feature 'test'
    src/racer/bench.rs:50         test::black_box(mask_sub_scopes(src));
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:50:9: 50:24 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:50         test::black_box(mask_sub_scopes(src));
                                  ^~~~~~~~~~~~~~~
    src/racer/scopes.rs:12:22: 12:30 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
    src/racer/scopes.rs:12 fn find_close<'a, A>(mut iter: A, open: u8, close: u8, level_end: u32) -> Option<usize>
                                                ^~~~~~~~
    src/racer/scopes.rs:117:42: 117:43 warning: unused variable: `i`, #[warn(unused_variables)] on by default
    src/racer/scopes.rs:117     match s.char_indices().rev().find(|&(i, c)| !util::is_ident_char(c)) {
                                                                     ^
    src/racer/nameres.rs:312:20: 312:35 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/nameres.rs:312     let srcpaths = std::os::getenv("RUST_SRC_PATH").unwrap_or("".to_string());
                                                ^~~~~~~~~~~~~~~
    src/racer/nameres.rs:487:20: 487:35 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/nameres.rs:487     let srcpaths = std::os::getenv("RUST_SRC_PATH").unwrap();
                                                ^~~~~~~~~~~~~~~
    src/racer/nameres.rs:761:26: 761:41 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/nameres.rs:761     let srcpaths = match std::os::getenv("RUST_SRC_PATH") { 
                                                      ^~~~~~~~~~~~~~~
    src/racer/test.rs:18:7: 18:26 warning: use of deprecated item: renamed to `write_all`, #[warn(deprecated)] on by default
    src/racer/test.rs:18     f.write(s.as_bytes()).unwrap();
                               ^~~~~~~~~~~~~~~~~~~
    src/racer/bench.rs:3:5: 3:36 warning: unused import, #[warn(unused_imports)] on by default
    src/racer/bench.rs:3 use std::old_io::fs::PathExtensions;
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/racer/bench.rs:13:30: 13:36 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/bench.rs:13     let mut src_path = match getenv("RUST_SRC_PATH") {
                                                       ^~~~~~
    src/racer/bench.rs:1:1: 1:19 warning: use of unstable library feature 'test'
    src/racer/bench.rs:1 extern crate test;
                         ^~~~~~~~~~~~~~~~~~
    src/racer/bench.rs:1:1: 1:19 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:1 extern crate test;
                         ^~~~~~~~~~~~~~~~~~
    src/racer/bench.rs:25:7: 27:7 warning: use of unstable library feature 'test'
    src/racer/bench.rs:25     b.iter(|| {
    src/racer/bench.rs:26         test::black_box(code_chunks(src).collect::<Vec<_>>());
    src/racer/bench.rs:27     });
    src/racer/bench.rs:25:7: 27:7 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:25     b.iter(|| {
    src/racer/bench.rs:26         test::black_box(code_chunks(src).collect::<Vec<_>>());
    src/racer/bench.rs:27     });
    src/racer/bench.rs:26:9: 26:24 warning: use of unstable library feature 'test'
    src/racer/bench.rs:26         test::black_box(code_chunks(src).collect::<Vec<_>>());
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:26:9: 26:24 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:26         test::black_box(code_chunks(src).collect::<Vec<_>>());
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:33:7: 35:7 warning: use of unstable library feature 'test'
    src/racer/bench.rs:33     b.iter(|| {
    src/racer/bench.rs:34         test::black_box(iter_stmts(src).collect::<Vec<_>>());
    src/racer/bench.rs:35     });
    src/racer/bench.rs:33:7: 35:7 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:33     b.iter(|| {
    src/racer/bench.rs:34         test::black_box(iter_stmts(src).collect::<Vec<_>>());
    src/racer/bench.rs:35     });
    src/racer/bench.rs:34:9: 34:24 warning: use of unstable library feature 'test'
    src/racer/bench.rs:34         test::black_box(iter_stmts(src).collect::<Vec<_>>());
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:34:9: 34:24 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:34         test::black_box(iter_stmts(src).collect::<Vec<_>>());
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:41:7: 43:7 warning: use of unstable library feature 'test'
    src/racer/bench.rs:41     b.iter(|| {
    src/racer/bench.rs:42         test::black_box(mask_comments(src));
    src/racer/bench.rs:43     });
    src/racer/bench.rs:41:7: 43:7 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:41     b.iter(|| {
    src/racer/bench.rs:42         test::black_box(mask_comments(src));
    src/racer/bench.rs:43     });
    src/racer/bench.rs:42:9: 42:24 warning: use of unstable library feature 'test'
    src/racer/bench.rs:42         test::black_box(mask_comments(src));
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:42:9: 42:24 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:42         test::black_box(mask_comments(src));
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:49:7: 51:7 warning: use of unstable library feature 'test'
    src/racer/bench.rs:49     b.iter(|| {
    src/racer/bench.rs:50         test::black_box(mask_sub_scopes(src));
    src/racer/bench.rs:51     });
    src/racer/bench.rs:49:7: 51:7 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:49     b.iter(|| {
    src/racer/bench.rs:50         test::black_box(mask_sub_scopes(src));
    src/racer/bench.rs:51     });
    src/racer/bench.rs:50:9: 50:24 warning: use of unstable library feature 'test'
    src/racer/bench.rs:50         test::black_box(mask_sub_scopes(src));
                                  ^~~~~~~~~~~~~~~
    src/racer/bench.rs:50:9: 50:24 help: add #![feature(test)] to the crate attributes to silence this warning
    src/racer/bench.rs:50         test::black_box(mask_sub_scopes(src));
                                  ^~~~~~~~~~~~~~~
    src/racer/scopes.rs:12:22: 12:30 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
    src/racer/scopes.rs:12 fn find_close<'a, A>(mut iter: A, open: u8, close: u8, level_end: u32) -> Option<usize>
                                                ^~~~~~~~
    src/racer/scopes.rs:117:42: 117:43 warning: unused variable: `i`, #[warn(unused_variables)] on by default
    src/racer/scopes.rs:117     match s.char_indices().rev().find(|&(i, c)| !util::is_ident_char(c)) {
                                                                     ^
    src/racer/nameres.rs:312:20: 312:35 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/nameres.rs:312     let srcpaths = std::os::getenv("RUST_SRC_PATH").unwrap_or("".to_string());
                                                ^~~~~~~~~~~~~~~
    src/racer/nameres.rs:487:20: 487:35 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/nameres.rs:487     let srcpaths = std::os::getenv("RUST_SRC_PATH").unwrap();
                                                ^~~~~~~~~~~~~~~
    src/racer/nameres.rs:761:26: 761:41 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/nameres.rs:761     let srcpaths = match std::os::getenv("RUST_SRC_PATH") { 
                                                      ^~~~~~~~~~~~~~~
    src/racer/test.rs:18:7: 18:26 warning: use of deprecated item: renamed to `write_all`, #[warn(deprecated)] on by default
    src/racer/test.rs:18     f.write(s.as_bytes()).unwrap();
                               ^~~~~~~~~~~~~~~~~~~
    src/racer/bench.rs:3:5: 3:36 warning: unused import, #[warn(unused_imports)] on by default
    src/racer/bench.rs:3 use std::old_io::fs::PathExtensions;
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/racer/bench.rs:13:30: 13:36 warning: use of deprecated item: use env::var or env::var_string instead, #[warn(deprecated)] on by default
    src/racer/bench.rs:13     let mut src_path = match getenv("RUST_SRC_PATH") {
                                                       ^~~~~~
         Running target/racer-c8594559178fcd05

    running 99 tests
    test racer::codecleaner::removes_a_comment_with_a_dbl_quote_in_it ... ok
    test racer::codecleaner::handles_nesting_of_block_comments ... ok
    test racer::codecleaner::removes_multiline_comment ... ok
    test racer::codecleaner::removes_string_contents ... ok
    test racer::codecleaner::removes_a_comment ... ok
    test racer::codecleaner::removes_char_contents ... ok
    test racer::codecleaner::handles_tricky_bit_from_str_rs ... ok
    test racer::codecleaner::removes_string_with_escaped_dblquote_in_it ... ok
    test racer::codecleaner::removes_string_with_escaped_slash_before_dblquote_in_it ... ok
    test racer::codecleaner::removes_string_contents_with_a_comment_in_it ... ok
    test racer::codeiter::iterates_lambda_arg ... ok
    test racer::codeiter::iterates_half_open_subscope_if_is_the_last_thing ... ok
    test racer::codeiter::iterates_inner_scope ... ok
    test racer::codeiter::iterates_macro_invocation ... ok
    test racer::codeiter::iterates_macro ... ok
    test racer::codeiter::iterates_single_use_stmts ... ok
    test racer::codeiter::iterates_use_stmt_over_two_lines ... ok
    test racer::codeiter::iterates_module_attribute ... ok
    test racer::codeiter::iterates_use_stmt_without_the_prefix ... ok
    test racer::codeiter::iterates_while_stmt ... ok
    test racer::nameres::does_it ... ok
    test racer::scopes::coords_to_point_works ... ok
    test racer::scopes::expand_search_expr_finds_ident ... ok
    test racer::ast::ast_sandbox ... FAILED
    test racer::scopes::expand_search_expr_handles_a_function_arg ... ok
    test racer::scopes::expand_search_expr_handles_chained_calls ... ok
    test racer::scopes::expand_search_expr_handles_inline_closures ... ok
    test racer::scopes::finds_end_of_struct_scope ... ok
    test racer::scopes::expand_search_expr_handles_pos_at_end_of_search_str ... ok
    test racer::scopes::get_start_of_pattern_handles_variant ... ok
    test racer::scopes::masks_out_comments ... ok
    test racer::scopes::get_start_of_pattern_handles_variant2 ... ok
    test racer::scopes::test_point_to_coords ... ok
    test racer::scopes::test_scope_start ... ok
    test racer::scopes::test_scope_start_handles_sub_scopes ... ok
    test racer::scopes::finds_subnested_module ... ok
    test racer::test::completes_pub_fn_locally ... ok
    test racer::test::completes_via_parent_scope_let ... ok
    test racer::test::completes_fn ... ok
    test racer::test::completes_local_scope_let ... ok
    test racer::test::completes_struct_field_via_assignment ... ok
    test racer::test::destructures_a_tuplestruct ... ok
    test racer::test::finds_definition_of_const ... ok
    test racer::test::finds_definition_of_lambda_argument ... FAILED
    test racer::test::finds_definition_of_let_tuple ... ok
    test racer::test::doesnt_find_if_let_if_not_in_the_subscope ... ok
    test racer::test::finds_definition_of_static ... ok
    test racer::test::finds_enum ... ok
    test racer::test::finds_fn_arg ... ok
    test racer::test::differentiates_type_and_value_namespaces ... ok
    test racer::test::finds_fn_arg_in_incomplete_fn ... ok
    test racer::test::finds_if_let_ident_defn ... ok
    test racer::test::finds_inline_fn ... ok
    test racer::test::finds_match_arm_var ... ok
    test racer::test::finds_glob_imported_enum_variant ... ok
    test racer::test::finds_match_arm_var_in_scope ... ok
    test racer::test::finds_impl_fn ... ok
    test racer::test::finds_defn_of_struct_field ... ok
    test racer::test::finds_a_generic_retval_from_a_function ... ok
    test racer::test::finds_field_type ... ok
    test racer::test::destructures_a_tuplestruct_with_generic_arg ... ok
    test racer::test::finds_trait ... ok
    test racer::test::finds_type ... ok
    test racer::test::finds_match_arm_var_with_nested_match ... ok
    test racer::test::finds_rebound_var_in_iflet ... ok
    test racer::test::finds_namespaced_enum_variant ... ok
    test racer::test::finds_templated_impl_fn ... ok
    test racer::test::finds_nested_submodule_file ... ok
    test racer::test::finds_type_of_tuple_member_in_fn_arg ... ok
    test racer::test::finds_type_of_tuple_member_via_let_expr ... ok
    test racer::test::follows_arg_to_enum_method ... ok
    test racer::test::finds_type_of_tuple_member_via_let_type ... ok
    thread '<unnamed>' panicked at 'position 0 does not resolve to a source locationtest racer::test::finds_trait_method ... ok
    ', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/codemap.rs:540
    test racer::test::finds_type_of_tuple_member_via_fn_retval ... ok
    test racer::test::follows_arg_to_method ... ok
    test racer::test::follows_chained_method_call ... ok
    test racer::test::follows_self_to_method_when_call_on_new_line ... FAILED
    test racer::test::follows_self_to_method ... ok
    test racer::test::follows_use ... ok
    test racer::test::follows_use_glob ... ok
    test racer::test::follows_self_to_trait_method ... ok
    test racer::test::follows_fn_to_method ... ok
    test racer::test::follows_use_as ... ok
    test racer::test::handles_dotdot_before_searchstr ... ok
    test racer::test::follows_self_use ... ok
    test racer::test::follows_let_method_call ... ok
    test racer::typeinf::generates_skeleton_for_mod ... ok
    test racer::util::txt_matches_matches_stuff ... ok
    test racer::test::follows_use_to_impl ... ok
    test racer::test::follows_use_to_inline_mod ... ok
    test racer::test::uses_generic_arg_to_resolve_trait_method ... FAILED
    test racer::test::gets_type_via_match_arm ... ok
    test racer::test::handles_an_enum_option_style_return_type ... ok
    test racer::test::handles_if_let ... ok
    test racer::test::handles_if_let_as_expression ... ok
    test racer::bench::bench_code_chunks     ... ignored
    test racer::bench::bench_iter_stmts      ... ignored
    test racer::bench::bench_mask_comments   ... ignored
    test racer::bench::bench_mask_sub_scopes ... ignored

    failures:

    ---- racer::ast::ast_sandbox stdout ----
        stmt Spanned { node: StmtDecl(Spanned { node: DeclItem(Item { ident: phil#0, attrs: [], id: 4294967295, node: ItemExternCrate(Some(("myarse", CookedStr))), vis: Inherited, span: Span { lo: BytePos(0), hi: BytePos(30), expn_id: ExpnId(4294967295) } }), span: Span { lo: BytePos(0), hi: BytePos(30), expn_id: ExpnId(4294967295) } }, 4294967295), span: Span { lo: BytePos(0), hi: BytePos(30), expn_id: ExpnId(4294967295) } } 
    thread 'racer::ast::ast_sandbox' panicked at '', src/racer/ast.rs:1083

    ---- racer::test::finds_definition_of_lambda_argument stdout ----
        thread 'racer::test::finds_definition_of_lambda_argument' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:362

    ---- racer::test::follows_self_to_method_when_call_on_new_line stdout ----
        thread 'racer::test::follows_self_to_method_when_call_on_new_line' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:362

    ---- racer::test::uses_generic_arg_to_resolve_trait_method stdout ----
        thread 'racer::test::uses_generic_arg_to_resolve_trait_method' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:362

    failures:
        racer::ast::ast_sandbox
        racer::test::finds_definition_of_lambda_argument
        racer::test::follows_self_to_method_when_call_on_new_line
        racer::test::uses_generic_arg_to_resolve_trait_method

    test result: FAILED. 91 passed; 4 failed; 4 ignored; 0 measured

    thread '<main>' panicked at 'Some tests failed', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libtest/lib.rs:256

In addition, the `complete` test doesn't succeed:

    $ ./target/release/racer complete std::io::B
    Sorry, I didn't understand command 
    usage: ./target/release/racer complete linenum charnum fname
    or:    ./target/release/racer find-definition linenum charnum fname
    or:    ./target/release/racer complete fullyqualifiedname   (e.g. std::io::)
    or:    ./target/release/racer prefix linenum charnum fname

    $ ./target/release/racer complete std::old_io::B
    Sorry, I didn't understand command 
    usage: ./target/release/racer complete linenum charnum fname
    or:    ./target/release/racer find-definition linenum charnum fname
    or:    ./target/release/racer complete fullyqualifiedname   (e.g. std::io::)
    or:    ./target/release/racer prefix linenum charnum fname

**Comment by phildawes** [comment]
Hi @fitzgen, What platform/environment is this on?
-Thanks

**Comment by fitzgen** [comment]
OSX Yosemite.

Can give more info when not on my phone.

**Comment by krzat** [comment]
I have the same "Sorry, I didn't understand command" on release on windows too, but it's probably Rust bug since debug build works fine. Something is wrong with the match, because
```
    if command == "complete" {
        complete(&match_fn);
        return;
    }
```
works fine.

**Comment by KaiserY** [comment]
Maybe the same problem, on Linux I got this:

./target/release/racer complete std::io::B
Illegal instruction (core dumped)

Platform: Fedora 21 x86_64

**Comment by renato-zannon** [comment]
@KaiserY @krzat  the segfault and "Sorry, I didn't understand command" were fixed (actually, worked around) recently! Could you try building again?

**Comment by renato-zannon** [comment]
@fitzgen I couln't reproduce the test failures with `rustc 1.0.0-nightly (74b874071 2015-02-08 00:24:03 +0000)` on linux-x86_64. Can you test again with a newer nightly and updated racer?

**Comment by KaiserY** [comment]
@renato-zannon Well, updated your workaround and all went well, thx for the fix.

**Comment by fitzgen** [comment]
@renato-zannon puled latest racer and latest rust and tests pass now, but I don't get any completions:

    $ export RUST_SRC_PATH=/Users/fitzgen/src/rust

    $ ./target/release/racer complete std::io::B

    $ ./target/release/racer complete std::old_io::B

**Comment by renato-zannon** [comment]
@fitzgen You need to point `RUST_SRC_PATH` to the `src` directory inside the rust distribution, not on the root

**Comment by fitzgen** [comment]
@renato-zannon ah, ok it works now! Thanks!
