### ISSUE TITLE
Crashes when completing std::libc::

### ISSUE THREAD

**Issue by yohanesu** [phildawes/racer#151]
Hi!

I've been having this issue since I installed racer a few days ago and today I did a git pull and rebuilt racer but still the same issue exists.

mm@JMBA-DEV:~/rust/racer$ target/release/racer complete std::libc::
bogofile:1:9: 1:14 error: file not found for module `types`
bogofile:1 pub mod types ;
                   ^~~~~
bogofile:1:9: 1:14 help: name the file either types.rs or types/mod.rs inside the directory "."
bogofile:1 pub mod types ;
                   ^~~~~
thread '<unnamed>' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/parse/parser.rs:971
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:362

**Comment by phildawes** [comment]
Hi @yohanesu ,
For the record, I get a recursive loop when I complete std::libc::
Marking as bug

**Comment by yohanesu** [comment]
Yes, that was what I meant. Not crash.. It uses 100% for a long time and eventually exits.

**Comment by phildawes** [comment]
cool thanks

**Comment by phildawes** [comment]
I think this is fixed now, closing
