### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ReanGD** [phildawes/racer#154]
$ rustc --version
rustc 1.0.0-nightly (b9ba643b7 2015-02-13 21:15:39 +0000)

$ cargo build --release
   Compiling racer v0.0.1 (file:///home/tmp/racer/racer)
src/racer/nameres.rs:312:20: 312:40 error: unresolved name `std::env::var_string`
src/racer/nameres.rs:312     let srcpaths = std::env::var_string("RUST_SRC_PATH").unwrap_or("".to_string());
                                            ^~~~~~~~~~~~~~~~~~~~
src/racer/nameres.rs:487:20: 487:40 error: unresolved name `std::env::var_string`
src/racer/nameres.rs:487     let srcpaths = std::env::var_string("RUST_SRC_PATH").unwrap();
                                            ^~~~~~~~~~~~~~~~~~~~
src/racer/nameres.rs:761:26: 761:46 error: unresolved name `std::env::var_string`
src/racer/nameres.rs:761     let srcpaths = match std::env::var_string("RUST_SRC_PATH") { 
                                                  ^~~~~~~~~~~~~~~~~~~~
src/main.rs:155:8: 155:28 error: unresolved name `std::env::var_string`
src/main.rs:155     if std::env::var_string("RUST_SRC_PATH").is_err() {
                       ^~~~~~~~~~~~~~~~~~~~
error: aborting due to 4 previous errors
Could not compile `racer`.

`std::env::var_string` is renamed to `std::env::var`:
https://github.com/lifthrasiir/rust-encoding/commit/b6b04585e2ad6424c9380b00a33238d669274025

**Comment by ebfe** [comment]
#152

**Comment by ReanGD** [comment]
Sorry for the duplicate. Close
