### ISSUE TITLE
Racer vim fails silently if RUST_SRC_PATH is not set

### ISSUE THREAD

**Issue by jakerr** [phildawes/racer#160]
For example when I `gd` with cursor over a symbol like
```rust
use std::sync::Arc;
//             ^ cursor here
```

All I see is a message that says
```
"src/main.rs.racertmp" [New] 84L, 2057C written
```

It turns out I'd mistakenly omitted `export` before `RUST_SRC_PATH = ...` in my `.zshrc`
An error message would be nice.

**Comment by jakerr** [comment]
I'm going to take a look at adding a quick error and will send a PR.

**Comment by norcalli** [comment]
You should probably close this since the PR was merged.

**Comment by petevine** [comment]
Is there documentation on which parts of rust source are absolutely necessary for RUST_SRC_PATH?

Thx

**Comment by phildawes** [comment]
Hi @petevine. I'm not sure what you mean by this question, do you need to
trim down your rust source directory because of space?

**Comment by petevine** [comment]
Yes, running a little low on an SD card system.

**Comment by phildawes** [comment]
Basically you need enough source so that racer can track down the
completions for the thing you are trying to complete. This depends on the
query, so there is no hard/fast rule.

**Comment by jonas-schievink** [comment]
@petevine I'll take a wild guess and say that you'll need at least `libcore`, `libcollections`, `libstd` (obviously), maybe the `liballoc*` crates, and `libtest` if you're doing benchmarks. Things like `libterm` aren't supposed to be used from your code (the crates.io version should be used instead), so you can probably remove them.

I also don't think racer needs anything outside the `src` directory. And you can most likely remove the `rustc_*` crates, all `lib*test` crates, all submodules, and `doc` as well.

If you cloned the repository, you can do `git clone --depth 1 ...` instead to prevent downloading the entire history.

**Comment by petevine** [comment]
Thanks, that's exactly what I meant - the minimum needed to do all completions.

**Comment by jonas-schievink** [comment]
I just noticed that this won't allow "all" completions: If you write compiler plugins, the `rustc_*` crates are necessary. But since they're probably the largest crates, you might want to remove them if you don't write plugins.

I also haven't tested this configuration, but it looks like a good starting point at least. You'll have to experiment a bit ;)
