### ISSUE TITLE
racer crashes when an invalid file is given to it

### ISSUE THREAD

**Issue by bollu** [phildawes/racer#162]
looks like libsyntax panics when you pass a syntactically invalid rust file to RACER. I'm trying to convert RACER in a library, so it _cannot_ crash, since the crash then propagates through FFI boundaries, tearing *everything* down with it.  Does anyone know any solution to this?

**Comment by phildawes** [comment]
Hi @bollu, I think most of the crashyness should be cleaned up now. If you come across new crashes, could you open a bug (or re-open this one) with a stack dump please? 
Thanks!
