### ISSUE TITLE
Compile error in Windows

### ISSUE THREAD

**Issue by smallb** [phildawes/racer#167]
f:\OpenSource\racer>cargo build --release
   Compiling racer v0.0.1 (file:///F:/OpenSource/racer)
src\racer\scopes.rs:15:21: 15:27 error: illegal suffix `usize` for numeric literal
src\racer\scopes.rs:15     let mut count = 0usize;
                                           ^~~~~~
src\racer\scopes.rs:230:21: 230:27 error: illegal suffix `usize` for numeric literal
src\racer\scopes.rs:230     let mut start = 0usize;
                                            ^~~~~~
src\racer\scopes.rs:231:19: 231:25 error: illegal suffix `usize` for numeric literal
src\racer\scopes.rs:231     let mut pos = 0usize;
                                          ^~~~~~
src\racer\ast.rs:210:33: 210:39 error: illegal suffix `usize` for numeric literal
src\racer\ast.rs:210                     let mut i = 0usize;
                                                     ^~~~~~
src\racer\nameres.rs:857:29: 857:43 error: incorrect slicing expression: `[..]`
src\racer\nameres.rs:857     if (is_exact_match && (&searchstr[..]) == "std") || (!is_exact_match && "std".starts_with(searchstr)) {
                                                     ^~~~~~~~~~~~~~
src\racer\nameres.rs:857:29: 857:43 note: use `expr[]` to construct a slice of the whole of expr
src\racer\nameres.rs:857     if (is_exact_match && (&searchstr[..]) == "std") || (!is_exact_match && "std".starts_with(searchstr)) {
                                                     ^~~~~~~~~~~~~~
src\racer\util.rs:130:19: 130:28 error: incorrect slicing expression: `[..]`
src\racer\util.rs:130         out.push(&item[..]);
                                        ^~~~~~~~~
src\racer\util.rs:130:19: 130:28 note: use `expr[]` to construct a slice of the whole of expr
src\racer\util.rs:130         out.push(&item[..]);
                                        ^~~~~~~~~
src\racer\matchers.rs:55:21: 55:27 error: illegal suffix `usize` for numeric literal
src\racer\matchers.rs:55     let mut start = 0usize;
                                             ^~~~~~
src\racer\test.rs:12:17: 12:23 error: incorrect slicing expression: `[..]`
src\racer\test.rs:12     p.push_str(&s[..]);
                                     ^~~~~~
src\racer\test.rs:12:17: 12:23 note: use `expr[]` to construct a slice of the whole of expr
src\racer\test.rs:12     p.push_str(&s[..]);
                                     ^~~~~~
src\main.rs:171:20: 171:32 error: incorrect slicing expression: `[..]`
src\main.rs:171     let command = &args[1][..];
                                   ^~~~~~~~~~~~
src\main.rs:171:20: 171:32 note: use `expr[]` to construct a slice of the whole of expr
src\main.rs:171     let command = &args[1][..];
                                   ^~~~~~~~~~~~
error: aborting due to 9 previous errors
Could not compile `racer`.

To learn more, run the command again with --verbose.

f:\OpenSource\racer>

**Comment by phildawes** [comment]
Which version or rust is this? It looks like it might be too old to run racer

**Comment by ChristophHusse** [comment]
I also had this error today on Windows. You need to update rust!

Fails on:

rustc 1.0.0-nightly (b63cee4a1 2015-02-14 17:01:11 +0000)

Succeeds on:

rustc 1.0.0-nightly (157614249 2015-03-01) (built 2015-03-02)

**Comment by smallb** [comment]
;)  thanks~~~

**Comment by l33tas** [comment]
Also doesn't build on linux with 
rustc 1.0.0-dev (built 2015-02-23)
cargo 0.0.1-pre-nightly (dd7c7bd 2015-03-04) (built 2015-03-04)

Getting a bunch of trait not implemented errors like this:

    error: the trait `core::ops::Fn<(char,)>` is not implemented for the type `&str` [E0277]
    src/racer/scopes.rs:62                     let newstart = blob.find("{").unwrap() + 1;

and a few different errors

**Comment by phildawes** [comment]
Hi @l33tas, your rustc is too old I'm afraid
Cheers,
Phil

**Comment by l33tas** [comment]
It works now. Thanks!
