### ISSUE TITLE
Is a Bug?

### ISSUE THREAD

**Issue by smallb** [phildawes/racer#178]
![qq 20150320105719](https://cloud.githubusercontent.com/assets/3250973/6745309/633ef900-cef0-11e4-8b75-a74a09141526.png)

the crash callstack

first:
00000000`6f90a040 41b901000000    mov     r9d,1
00000000`6f90a046 4889f9          mov     rcx,rdi
00000000`6f90a049 4c89fa          mov     rdx,r15
00000000`6f90a04c 4989e8          mov     r8,rbp
00000000`6f90a04f e83ce9feff      call    syntax_4e7c5e5c!ZN5parse5token5Token14is_any_keyword20h992ca26cdd22ceefLYRE+0x2b0 (00000000`6f8f8990)
00000000`6f90a054 4883bc24d001000001 cmp   qword ptr [rsp+1D0h],1

second:
00000000`6f8f8990 4157            push    r15
00000000`6f8f8992 4156            push    r14
00000000`6f8f8994 4155            push    r13
00000000`6f8f8996 4154            push    r12
00000000`6f8f8998 56              push    rsi
00000000`6f8f8999 57              push    rdi
00000000`6f8f899a 55              push    rbp
00000000`6f8f899b 53              push    rbx
00000000`6f8f899c 48b82836000000000000 mov rax,3628h
00000000`6f8f89a6 e865fc2000      call    syntax_4e7c5e5c!ZN3ext5quote2rt29_$LP$$RP$.ToSourceWithHygiene22to_source_with_hygiene20hc1285fd8dda96268tydE+0x14b0 (00000000`6fb08610)
00000000`6f8f89ab 4829c4          sub     rsp,rax
00000000`6f8f89ae 0f29b42410360000 movaps  xmmword ptr [rsp+3610h],xmm6
00000000`6f8f89b6 4589ce          mov     r14d,r9d

the end:
00000000`6fb08610 51              push    rcx
00000000`6fb08611 50              push    rax
00000000`6fb08612 483d00100000    cmp     rax,1000h
00000000`6fb08618 488d4c2418      lea     rcx,[rsp+18h]
00000000`6fb0861d 7219            jb      syntax_4e7c5e5c!ZN3ext5quote2rt29_$LP$$RP$.ToSourceWithHygiene22to_source_with_hygiene20hc1285fd8dda96268tydE+0x14d8 (00000000`6fb08638)
00000000`6fb0861f 4881e900100000  sub     rcx,1000h
00000000`6fb08626 48830900        or      qword ptr [rcx],0 ds:00000000`00040ef8=????????????????
00000000`6fb0862a 482d00100000    sub     rax,1000h
00000000`6fb08630 483d00100000    cmp     rax,1000h
00000000`6fb08636 77e7            ja      syntax_4e7c5e5c!ZN3ext5quote2rt29_$LP$$RP$.ToSourceWithHygiene22to_source_with_hygiene20hc1285fd8dda96268tydE+0x14bf (00000000`6fb0861f)
00000000`6fb08638 4829c1          sub     rcx,rax
00000000`6fb0863b 48830900        or      qword ptr [rcx],0
00000000`6fb0863f 58              pop     rax
00000000`6fb08640 59              pop     rcx

I think this code in rust's sources.

Rust\src\libsyntax\ext\quote.rs :

    // FIXME (Issue #16472): This should go away after ToToken impls
    // are revised to go directly to token-trees.
    trait ToSourceWithHygiene : ToSource {
        // Takes a thing and generates a string containing rust code
        // for it, encoding Idents as special byte sequences to
        // maintain hygiene across serialization and deserialization.
        fn to_source_with_hygiene(&self) -> String;
    }

**Comment by phildawes** [comment]
Does this happen with the latest rust nightly + racer? - Thanks!

**Comment by phildawes** [comment]
closing. Please re-open if still an issue. Thanks!
