### ISSUE TITLE
cannot compile on rustc 1.0.0-nightly (ecf8c64e1 2015-03-21) (built 2015-03-22)

### ISSUE THREAD

**Issue by jeremyjh** [phildawes/racer#179]
There are a couple of problems. We have lots of undeclared uses of Path. 

```
src/racer/ast.rs:338:50: 338:54 error: use of undeclared type name `Path`
src/racer/ast.rs:338 fn resolve_ast_path(path: &ast::Path, filepath: &Path, pos: usize) -> Option<Match> {
```

If I use std::path::Path everywhere, I still get an error:

```
trait `core::marker::Sized` is not implemented for the type `[u8]` 
```

This is on Ubuntu 14.04.

**Comment by Ell** [comment]
Getting this too, just pulled down nightly as of 03-22-2015.

**Comment by jan-hudec** [comment]
The reason for

    trait `core::marker::Sized` is not implemented for the type `[u8]`

is that `std::path::Path` is unsized type similar to `str` while analogue of `String` is `std::path::PathBuf`. Also the `join_many` function seems not to be there (documentation only shows it for `std::old_path::Path`).

**Comment by jan-hudec** [comment]
The `Path` is supposed to still be `std::old_path::Path`. There are two ways to get the code to compile:

1. Add imports for `std::old_path::Path` and other `old_io` traits that are no longer imported by default: `std::old_io::Reader`, `std::old_io::BufferPrelude` and `std::old_path::GenericPath`.

2. Port the code to the now stable new io. Here it's important to note, that `std::path::Path` is unsized type similar to `str`, so while in all places where `&Path` is used it is Ok, the functions in `src/racer/nameres.rs` that return `Vec<Path>` or `Option<Path>` have to use `std::path::PathBuf` instead. That also happens to be what `Path.join` returns. This needs porting the file code too, which is obviously some extra work, but it will have to be done anyway.

**Comment by oakes** [comment]
@jan-hudec I already ported the code to the new io, see #180.
