### ISSUE TITLE
Missing module racer::cargo

### ISSUE THREAD

**Issue by ruabmbua** [phildawes/racer#183]
I am trying to compile racer on beta 1.0.0, but it fails due to a missing module named `cargo`. It is imported from multiple locations and fails because of the missing module.

Maybe forgot to stage the `racer/cargo` module, and commit it?

**Comment by jroblak** [comment]
Getting the same issue. The cause is:
``` 
pub mod cargo; 
```
on line 16 of mod.rs

**Comment by phildawes** [comment]
Duh! I forgot to git add cargo.rs. Thanks for the heads-up; I've pushed it now
N.B. I don't think racer will work with rust-beta as it stands, because it uses unstable features and they're not allowed with the beta channel

**Comment by ruabmbua** [comment]
Thanks for solving. No it should not be a problem to build it in beta. The rust compiler itself uses unstable features, and there is an environment variable, to bypass the checking even in beta.
