### ISSUE TITLE
Could not compile racer with current rust 1.0.0-beta

### ISSUE THREAD

**Issue by Rydgel** [phildawes/racer#184]
The use of unstable features has been disabled.

```bash
src/main.rs:1:1: 1:66 error: unstable feature
src/main.rs:1 #![feature(collections, core, rustc_private, str_char, path_ext)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/main.rs:2:24: 2:45 error: unstable feature
src/main.rs:2 #![cfg_attr(not(test), feature(exit_status))] // we don't need exit_status feature when testing
                                     ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 2 previous errors
Could not compile `racer`.
```

A short term work-around would be to keep using rust-nightly for the time being.
But I think it will be cool for racer to support stable releases too.
What do you guys think of this?

**Comment by phildawes** [comment]
I agree it would be cool, but I'm not sure what's involved yet. Things like path.exists() are pretty useful to racer - hopefully path_ext will stabilize soon (or there will be a crates.io crate for it).

**Comment by AndrewGaspar** [comment]
I had the same negative reaction at first (just starting Rust, so this was an unpleasant surprise!). However, it seems like a lot of pretty core functionality is being blocked as "unstable". I would expect most of this stuff will be stabilized by the final 1.0 release. I would think racer should just wait and see what the final release of 1.0 holds, which racer should absolutely support.

**Comment by by90** [comment]
maybe all ide solution based on racer,that's mean...all guys should play rust without ide, until 1.0 release.

**Comment by by90** [comment]
http://doc.rust-lang.org/1.0.0-beta/std/path/struct.Path.html
for path.exists...here,it's stable.

**Comment by zsiciarz** [comment]
Not really, the [PathExt](http://doc.rust-lang.org/1.0.0-beta/std/fs/trait.PathExt.html) trait is unstable.

**Comment by phildawes** [comment]
Closing because racer is unlikely to be able to be built against rust beta as it relies on libsyntax internals that aren't in rust-beta. Hopefully we can do something for rust-1.0. 
N.B. For 1.0 we will probably need to fork rustc into its own crate since rustc won't be stable for 1.0. Either that or provide racer binaries.
