### ISSUE TITLE
\o/ Thanks! (and Cargo path support)

### ISSUE THREAD

**Issue by MarkSwanson** [phildawes/racer#185]
I'm really pleased you now support 'Go to Definition' for crates pulled in by Cargo.
It's super helpful when learning new APIs.

Request: I currently work on multiple crates that I'm building locally and use 'path' instead of 'git' to point to the crate/src. Please accept my vote to support 'path' next.

Thanks!

Example:
[dependencies.mylib]
path = "../mylib/"

in addition to how you search for git now:
[dependencies.mylib]
git = "ssh://mymachine/home/git_repos/mylib

**Comment by phildawes** [comment]
Hi Mark, Thanks, will do that next

**Comment by phildawes** [comment]
Hi Mark,
I've made an attempt at implementing this - could you give it a try please?
Also, what platform are you running on?
N.B. My implementation doesn't normalize the file path, so e.g. the resolved crate root filename in your example would be e.g. '/path/to/project/../mylib/src/lib.rs' 

Thanks!

**Comment by MarkSwanson** [comment]
Platform = linux + mac; both with vim.

Your changes work perfectly.
Thanks Phil!!!
