### ISSUE TITLE
Vim neocomplete integration

### ISSUE THREAD

**Issue by arnm** [phildawes/racer#194]
It would be nice if there were instructions on how to add the completions to popular completion engines.

I, for one, love [neocomplete](https://github.com/Shougo/neocomplete.vim), a Vim completion plugin. Here is what I have done so far to integrate racer completions as a source for neocomplete.

neocomplete calls the omnifunc, if it is available. This means that all one has to to do to provide racer completions as a source for neocomplete is to define input patterns for the FileType.

After setting up neocomplete and the racer plugin the following line should feed racer completions to neocomplete:

```vim
" if patter matches, local omnifunc will be called
if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.rust =
    \ '[^.[:digit:] *\t]\%(\.\|\::\)\%(\h\w*\)\?'
```

This allows for racer completions to be shown on  ```.``` and ```::```

Hopes this helps!

P.S I'm not a Vim expert. I mainly fiddle with stuff until it works :) But I'm definitely willing to help.

**Comment by 0X1A** [comment]
:+1: Instructions on how to integrate racer with neocomplete should be included

**Comment by lilydjwg** [comment]
But I did nothing except specifying `let g:racer_cmd = 'racer'` and I can see results in the neocomplete popup menu from racer :-)

**Comment by arnm** [comment]
@lilydjwg do you get the popup menu on `.` and on `::`?

**Comment by lilydjwg** [comment]
@arnm yes. In fact I get a popup menu while I'm typing all the time. I've checked items from racer completion do appear on `.` and `::`.

**Comment by leonardinius** [comment]
+1 on instructions

**Comment by Shougo** [comment]
I added default omni func pattern in neocomplete.  Thanks.

**Comment by softinio** [comment]
Thanks to the instructions here I have got it working, but when ever I use it creates a temporary file with an extension of .rs.racertmp. How do I stop it doing this or what do I need to do for it to removed automatically and merged into original file I am editing?

**Comment by phildawes** [comment]
The vim plugin should be removing these files, but I guess it probably
doesn't if racer fails to complete or something.
The emacs support currently puts the temporary files in the /tmp dir, so
vim support could do the same. There is an issue for this: #330

**Comment by Shougo** [comment]
I think it should be closed.

**Comment by Shougo** [comment]
@softinio I fixed the problem in https://github.com/phildawes/racer/issues/344.

**Comment by Shougo** [comment]
@phildawes I think it should be closed.
