### ISSUE TITLE
Racer basic completion example not working on Windows

### ISSUE THREAD

**Issue by bruno-medeiros** [phildawes/racer#196]
I tried to install and racer run the basic example:
`./target/release/racer complete std::io::B`
on windows, but it just outputs an empty line. On Linux it worked fine. 

I downloaded: rust-nightly-x86_64-pc-windows-gnu and rustc-nightly-src.tar (for the src/ folder), ran this on Cygwin:
`export RUST_SRC_PATH="D:/devel/tools.Rust/rustc-nightly/src" ; ./target/release/racer.exe complete std:io::` but just got an empty line of ouput.

Other racer commands seem to not be working either.

**Comment by phildawes** [comment]
Hi Bruno,
I'm afraid I don't have a windows box to try this on. 
Can anybody else help Bruno? Is racer working on windows at the moment?

Cheers,

Phil

**Comment by bruno-medeiros** [comment]
Ha, I need to clarify something that I misunderstood at first: I can get completion to work for symbols defined in my source file (didn't realize this at first).

What is definitely not showing up are completions for standard library elements. 

Perhaps it's something related to how RUST_SRC_PATH is read? If I put a bogus path there, I get the same behavior as the valid RUST_SRC_PATH, Racer won't complain that the path doesn't exist.

**Comment by axeoth** [comment]
I think the PATH should be passed as: RUST_SRC_PATH='/cygdrive/d/devel/tools.Rust/rustc-nightly/src'. See: http://stackoverflow.com/a/15994344

**Comment by bruno-medeiros** [comment]
The fact that I ran Racer from Cygwin is irrelevant, as Racer is not a Cygwin app. If I run it from the windows shell, the result is the same.

**Comment by bruno-medeiros** [comment]
But maybe Racer is tripping up with the "D:" in the path variable though? Just a guess...

**Comment by bruno-medeiros** [comment]
Ok, nevermind, it's actually working now. I must have made some mistake originally, perhaps first putting the wrong path, and on later tries, having that typo in `complete std:io::`. My bad.
