### ISSUE TITLE
Issue with `#![no_std]`

### ISSUE THREAD

**Issue by GBGamer** [phildawes/racer#198]
I'm not sure if this is an actual bug, or I set something up wrong, but whenever I attempt to complete, I get the following message:

```
Company: Back-end racer-company-complete error ".../racer exited with status 101" with args (candidates )
```

**Comment by phildawes** [comment]
Hi @GBGamer. Does the racer binary run ok on the command line?
If so, post your emacs settings here

**Comment by GBGamer** [comment]
I've figured it out; racer (I guess), currently doesn't work with `#![no_std]`, as it works when I use it on another project, but not on my `#![no_std]` game. In the command line, it says:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(2) }', .../libcore/result.rs:768
```

**Comment by GBGamer** [comment]
In order to test this, run `racer complete 9 21` on this file: [gist][error].

[error]: https://gist.github.com/GBGamer/0bdbe9c8cc039798f11f

**Comment by phildawes** [comment]
Thanks @GBGamer - I'll check this out tonight

**Comment by GBGamer** [comment]
Okay, this bug is invalid. I figured out what is actually wrong: I used a tilde in `RUST_SRC_PATH`.

**Comment by GBGamer** [comment]
I'm really sorry...

**Comment by phildawes** [comment]
No worries, glad you sorted it
