### ISSUE TITLE
Questions about Racer integration input and output.

### ISSUE THREAD

**Issue by bruno-medeiros** [phildawes/racer#199]
This is not a bug report, but rather I have some questions about the usage of Racer for IDE integration. Some of it I couldn't figure out just by experimenting.
`usage: D:\devel\tools.Rust\racer\target\release\racer.exe complete linenum charnum fname`
What is charnum in here? Is it the column number? Is this a zero-based or one-based index?

On the output of complete:
`PREFIX 1,1,`
What does this mean and are the possible syntaxes of this response?

**Comment by phildawes** [comment]
Hi Bruno,
Charnum is 0 indexed column, linenum is 1 indexed line.  This is how emacs works and I started with that. The PREFIX output tells the editor how many characters before the complete are part of the completed term.
Hope that helps

**Comment by bruno-medeiros** [comment]
Another question, in the MATCH output, for example:
`MATCH other;other(${1:foo: i32});19;3;D:\devel\DDT\_runtime\RustProj\src\main.rs;Function;fn other(foo: i32) {`
The 6th field ("Function" in example above), which I guess denotes the kind of element, what are all the possible values for that field?

**Comment by phildawes** [comment]
Hi Bruno,
These come from the enum in
https://github.com/phildawes/racer/blob/master/src/racer/mod.rs#L22

**Comment by bruno-medeiros** [comment]
Some follow up questions:
In what code/situation does one get a `Crate` match?
Why does Racer `complete` command show no completions if there is no prefix? (one would imagine it would show all available symbols in the scope)

BTW, I've essentially finished the Racer integration into Eclipse (https://raw.githubusercontent.com/RustDT/RustDT/master/documentation/screenshots/Feature_ContentAssist.png) - both for Code Completion and Find Definition. Seems to be working fine, looking forward to releasing it soon. I'm glad a tool such as Racer is already available for Rust! :)
