### ISSUE TITLE
RUST_SRC_PATH does not like tilde

### ISSUE THREAD

**Issue by drewcrawford** [phildawes/racer#200]
```bash
 #works
RUST_SRC_PATH="/Users/drew/Code/rust/src/" racer complete std::io::B
#doesn't work
RUST_SRC_PATH="~/Code/rust/src/" racer complete std::io::B
```

I claim tilde paths should "just work", but if not that, then at least something exciting should happen that suggests there's something wrong with the path, rather than silent exit with return code 0.

**Comment by GBGamer** [comment]
Try typing `echo ~` and tell me what happens. Make sure not to quote the tilde.

**Comment by drewcrawford** [comment]
```bash
$ echo ~
/Users/drew
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by GBGamer** [comment]
Okay, now try doing the RUST_SRC_PATH without the quotes. That should temporarily fix it as I try to figure out what's wrong.

**Comment by GBGamer** [comment]
Well, this seems to be due to `std::path` not expanding the tilde, and in fact was the cause of an issue I filed earlier. Just use the full path from now on, I guess, is my advice.

**Comment by phildawes** [comment]
Hi @drewcrawford, @GBGamer
I think '~' is something that the shell expands, it's not a valid path. By putting the env var quotes the shell doesn't expand it. 
A better error message is a good idea, thanks, I'll add it.

**Comment by phildawes** [comment]
done
