### ISSUE TITLE
Racer fails with certain completion - using std::io module

### ISSUE THREAD

**Issue by jaxx** [phildawes/racer#201]
Hello,

I have a problem with Racer in Windows. After I type this line
`let stdin = std::io::stdin().` and insert dot, then Racer stops working. If this helps I see in Sublime console following line: `failed: exit_code: 255 b'PREFIX 28,28,\n'`. But I don't have problem with other modules and completion works ok. I used old_io so far, but it was removed from Rust and now I must use correct io module.

Image
![capture](https://cloud.githubusercontent.com/assets/723258/7188060/c6342db2-e47d-11e4-955e-98fbf64606cd.PNG)

**Comment by phildawes** [comment]
Hi @jaxx. Thanks for filing this, your test case helped me isolate the problem to the handling of 'super::"

**Comment by jaxx** [comment]
Now it works great, thanks!
