### ISSUE TITLE
Racer build fails

### ISSUE THREAD

**Issue by rohitjoshi** [phildawes/racer#202]
OS: OSX 10.10.3
    cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-03-31)
    rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)
    git branch: master , checked out today

$cargo build
   Compiling rustc-serialize v0.3.12
   Compiling toml v0.1.20
   Compiling racer v0.0.1 (file:///projects/rust/racer)
src/racer/ast.rs:41:17: 41:37 error: type `&mut syntax::parse::parser::Parser<'_>` does not implement any method in scope named `parse_stmt_nopanic`
src/racer/ast.rs:41         match p.parse_stmt_nopanic() {
                                    ^~~~~~~~~~~~~~~~~~~~
src/racer/ast.rs:54:13: 54:18 error: mismatched types:
 expected `syntax::ast::Crate`,
    found `core::result::Result<_, _>`
(expected struct `syntax::ast::Crate`,
    found enum `core::result::Result`) [E0308]
src/racer/ast.rs:54             Ok(e) => Some(e),
                                ^~~~~
src/racer/ast.rs:55:13: 55:28 error: mismatched types:
 expected `syntax::ast::Crate`,
    found `core::result::Result<_, _>`
(expected struct `syntax::ast::Crate`,
    found enum `core::result::Result`) [E0308]
src/racer/ast.rs:55             Err(FatalError) => {
                                ^~~~~~~~~~~~~~~
src/racer/snippets.rs:40:17: 40:27 error: mismatched types:
 expected `syntax::ptr::P<syntax::ast::ImplItem>`,
    found `core::result::Result<_, _>`
(expected struct `syntax::ptr::P`,
    found enum `core::result::Result`) [E0308]
src/racer/snippets.rs:40                 Ok(method) => {
                                         ^~~~~~~~~~
src/racer/snippets.rs:55:17: 55:32 error: mismatched types:
 expected `syntax::ptr::P<syntax::ast::ImplItem>`,
    found `core::result::Result<_, _>`
(expected struct `syntax::ptr::P`,
    found enum `core::result::Result`) [E0308]
src/racer/snippets.rs:55                 Err(FatalError) => {
                                         ^~~~~~~~~~~~~~~
src/racer/snippets.rs:41:27: 41:38 error: the type of this value must be known in this context
src/racer/snippets.rs:41                     match method.node {
                                                   ^~~~~~~~~~~
error: aborting due to 6 previous errors
Could not compile `racer`.

**Comment by contradictioned** [comment]
+1

**Comment by rillian** [comment]
Yesterday's rustc-1.0.0-beta.2 gets further, building except for unstable feature errors.

```
$ cargo build
   Compiling rustc-serialize v0.3.12
   Compiling toml v0.1.20
   Compiling racer v0.0.1 (file:///Users/giles/.local/racer)
src/main.rs:1:1: 1:66 error: unstable feature
src/main.rs:1 #![feature(collections, core, rustc_private, str_char, path_ext)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/main.rs:2:24: 2:45 error: unstable feature
src/main.rs:2 #![cfg_attr(not(test), feature(exit_status))] // we don't need exit_status feature when testing
                                     ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 2 previous errors
Could not compile `racer`.

To learn more, run the command again with --verbose.
tamias:racer giles$ cargo build --release
   Compiling rustc-serialize v0.3.12
   Compiling toml v0.1.20
   Compiling racer v0.0.1 (file:///Users/giles/.local/racer)
src/main.rs:1:1: 1:66 error: unstable feature
src/main.rs:1 #![feature(collections, core, rustc_private, str_char, path_ext)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/main.rs:2:24: 2:45 error: unstable feature
src/main.rs:2 #![cfg_attr(not(test), feature(exit_status))] // we don't need exit_status feature when testing
                                     ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 2 previous errors
Could not compile `racer`.

To learn more, run the command again with --verbose.
$ rustc --version
rustc 1.0.0-beta.2 (e9080ec39 2015-04-16) (built 2015-04-16)
```

**Comment by phildawes** [comment]
Oh that's interesting, I didn't realise there was a beta 2 out. It may be feasible to make racer work with this beta (and therefore 1.0!) by depending on https://github.com/erickt/rust-syntex instead of libsyntax.

**Comment by phildawes** [comment]
Closing - racer now builds with beta
