### ISSUE TITLE
Add loaded_racer variable for selective loading / avoiding reloading and feature testing in racer.vim

### ISSUE THREAD

**Issue by robertmeta** [phildawes/racer#206]
A pattern a lot of vim plugins follow is having a loaded variable that halts processing of the script if it has already been loaded, or if under some conditions the user wants it not to be loaded they can set the variable prior to script init. 

```viml
" This goes at the very top of racer.vim
if exists ("g:loaded_racer")
    finish
endif
let g:loaded_racer=1
```

It is common enough for required feature checks to also go on the if line: 

```viml
if exists("g:loaded_racer") || &cp || v:version < 700 
```

**Comment by Yamakaky** [comment]
Good idea

**Comment by Shougo** [comment]
Implemented.
