### ISSUE TITLE
Error when compiling - Unresolved import

### ISSUE THREAD

**Issue by Backman** [phildawes/racer#207]
```
error: unresolved import `std::num::Float`. There is no `Float` in `std::num`
use std::num::{Float, Int};
			   ^~~~~
error: unresolved import `std::num::Int`. There is no `Int` in `std::num`
use std::num::{Float, Int};
					  ^~~
error: unresolved import `std::ffi::AsOsStr`. There is no `AsOsStr` in `std::ffi`
use std::ffi::{AsOsStr, OsString};
			   ^~~~~~~
error: aborting due to 3 previous errors
Could not compile `rustc-serialize`.
```
I'm getting these errors when compiling racer.
Rust version: rustc 1.1.0-nightly (21f278a68 2015-04-23) (built 2015-04-24)
Cargo version: cargo 0.2.0-nightly (dac600c 2015-04-22) (built 2015-04-24)

**Comment by pataroose** [comment]
These seem to be issues with racer's `rustc-serialize` dependency, which is strange, because it seems to be building independently. Maybe it's a version issue?

**Comment by marvelm** [comment]
>cargo update
>cargo build

**Comment by pataroose** [comment]
That works, thanks.

**Comment by nyx** [comment]
TIL `cargo update` :+1:
