### ISSUE TITLE
Error when compiling - unstable feature

### ISSUE THREAD

**Issue by chessnokov** [phildawes/racer#209]
Downloading rustc-serialize v0.3.13
   Compiling rustc-serialize v0.3.13
   Compiling toml v0.1.20
   Compiling racer v0.0.1 (file:///home/chessnokov/workspace/src/github.com/phildawes/racer)
src/main.rs:1:1: 1:66 error: unstable feature
src/main.rs:1 #![feature(collections, core, rustc_private, str_char, path_ext)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/main.rs:2:24: 2:45 error: unstable feature
src/main.rs:2 #![cfg_attr(not(test), feature(exit_status))] // we don't need exit_status feature when testing
                                     ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 2 previous errors
Could not compile `racer`.

**Comment by jaxx** [comment]
Racer does not work yet with beta version of Rust.

**Comment by unaxfromsibiria** [comment]
when expect the update for build on rust-beta? Use rustc 1.0.0-beta.4 (850151a75 2015-04-30) (built 2015-04-30).
```
$ cargo build
   Compiling racer v0.0.1 (file:///*/racer)
src/main.rs:1:1: 1:25 error: unstable feature
src/main.rs:1 #![feature(collections)]
              ^~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/main.rs:2:1: 2:22 error: unstable feature
src/main.rs:2 #![feature(path_ext)]
              ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/main.rs:3:1: 3:22 error: unstable feature
src/main.rs:3 #![feature(str_char)]
              ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/main.rs:5:24: 5:45 error: unstable feature
src/main.rs:5 #![cfg_attr(not(test), feature(exit_status))] // we don't need exit_status feature when testing
                                     ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 4 previous errors
Could not compile `racer`.

```

**Comment by phildawes** [comment]
Hi @unaxfromsibiria,
I'm working on this, so hopefully soon (few days maybe?). Currently I'm removing dependency on collections.

**Comment by phildawes** [comment]
My estimate was a bit long. This is now done!
