### ISSUE TITLE
Can't compile with nightly (27.04.2015) [syntax ToSource]

### ISSUE THREAD

**Issue by Survivor99** [phildawes/racer#213]
Well, it doesn't compile anymore with the newest nightly build, did they remove syntax::ext::quote::rt::ToSource?
![capture](https://cloud.githubusercontent.com/assets/9151604/7348374/51227566-ecf1-11e4-9edc-589160146de7.PNG)

**Comment by zsiciarz** [comment]
Yes, here's the relevant commit: https://github.com/rust-lang/rust/commit/6365080c5cd27b74ec87420c351a3e7bdcff988e
