### ISSUE TITLE
RUST_SRC_PATH reported as not existing on Windows

### ISSUE THREAD

**Issue by pvginkel** [phildawes/racer#223]
With the latest version on beta, Racer reports ``RUST_SRC_PATH`` as not existing while it is. The following change in ``util.rs`` fixed this:

```
 pub fn path_exists<P: AsRef<Path>>(path: P) -> bool {
-    File::open(path).is_ok()
+    is_dir(path.as_ref()) || File::open(path).is_ok()
 }
```

**Comment by phildawes** [comment]
Thanks @pvginkel, have pushed this change. I don't have a windows machine at home to work with so am relying on others to tell me what doesn't work.

**Comment by pvginkel** [comment]
You're welcome. Thanks for the fast response.
