### ISSUE TITLE
Racer doesn't seem to find sources for crates with hyphens in their name

### ISSUE THREAD

**Issue by Izzeri** [phildawes/racer#226]
Running Racer in RustDT (http://rustdt.github.io/), it seems Racer doesn't give suggestions for "rustc-serialize", which is linked as `extern crate rustc_serialize` even though the crate name itself is `rustc-serialize`.

**Comment by phildawes** [comment]
Thanks for the issue @Izzeri. Marked as bug, I'll will try to fix soon

**Comment by tafia** [comment]
@Izzeri, I think #271 fixes your issue.
Can you give it a try ? (the more tests, the better)

**Comment by Izzeri** [comment]
@tafia, I'll see if I can later today. Thanks for the fix! <3
