### ISSUE TITLE
Cannot compile with rustc 1.0.0-beta on Master

### ISSUE THREAD

**Issue by donaldpipowitch** [phildawes/racer#231]
````
$ cargo build --release
/...../.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.4.2/src/ptr.rs:110:9: 110:26 error: the trait `core::fmt::Pointer` is not implemented for the type `Box<T>` [E0277]
/...../.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.4.2/src/ptr.rs:110         fmt::Pointer::fmt(&self.ptr, f)
                                                                                                              ^~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `syntex_syntax`.
````

**Comment by CarlColglazier** [comment]
I am running into the same problem.

This is the line that is throwing the error: https://github.com/erickt/rust-syntex/blob/master/syntex_syntax/src/ptr.rs#L110

**Comment by damienrg** [comment]
What version of rustc do you use? It should work with  'rustc 1.0.0-beta.4 (850151a75 2015-04-30) (built 2015-04-30)'.

**Comment by CarlColglazier** [comment]
@daboross I was running `rustc 1.0.0-beta.3`. It works on `rustc 1.0.0-beta.4`.

**Comment by donaldpipowitch** [comment]
I had `rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)`. Will try a new one.

**Comment by donaldpipowitch** [comment]
`rustc 1.0.0-beta.4` works.

**Comment by donaldpipowitch** [comment]
It seems I can't find `/usr/local/src/rust/src` on Mac with installing Rust from the official installers. Any help?

**Comment by tafia** [comment]
You should not install it but clone the rust git repo I think

**Comment by donaldpipowitch** [comment]
Thanj you, I'll try it
