### ISSUE TITLE
pri doesn't complete to println!

### ISSUE THREAD

**Issue by ErwinJunge** [phildawes/racer#243]
I'm rather new to Rust, so not sure if this is an actual issue with racer, but from my limited experience I'd expect the result of
```
RUST_SRC_PATH=~/.multirust/toolchains/stable/src ./racer complete pri
```
to include stuff like `println!`. Instead, I'm getting no results at all. For completeness, the example in de docs works correctly:
```
RUST_SRC_PATH=~/.multirust/toolchains/stable/src ./racer complete std::io::B
MATCH BufReader,33,11,/home/erwin/.multirust/toolchains/stable/src/libstd/io/buffered.rs,Struct,pub struct BufReader<R> {
MATCH BufWriter,179,11,/home/erwin/.multirust/toolchains/stable/src/libstd/io/buffered.rs,Struct,pub struct BufWriter<W: Write> {
MATCH BufStream,442,11,/home/erwin/.multirust/toolchains/stable/src/libstd/io/buffered.rs,Struct,pub struct BufStream<S: Write> {
MATCH BufRead,516,10,/home/erwin/.multirust/toolchains/stable/src/libstd/io/mod.rs,Trait,pub trait BufRead: Read {
MATCH Broadcast,628,11,/home/erwin/.multirust/toolchains/stable/src/libstd/io/mod.rs,Struct,pub struct Broadcast<T, U> {
MATCH Bytes,746,11,/home/erwin/.multirust/toolchains/stable/src/libstd/io/mod.rs,Struct,pub struct Bytes<R> {
```

I've searched through the issues and this seems related to #45, but that was marked as solved.

**Comment by phildawes** [comment]
Hi @ErwinJunge, I'm afraid Racer doesn't support completion of macros yet, sorry.

**Comment by rkfg** [comment]
Then why to close the issue? Isn't it better to leave it open and label as an enhancement? I'm interested in Rust but without a proper completion it's a pain to write anything complex enough. I'd rather look into suggestions than search the documentation and sources (which is the last resort for me).
