### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by mbrt** [phildawes/racer#244]
I have setup a Docker image containing rust 1.0.0, vim and racer [here](https://registry.hub.docker.com/u/mbrt/vim-rust/). If it is useful, feel free to post a link to it.

**Comment by phildawes** [comment]
Nice! Have you posted this to rust reddit? 
http://www.reddit.com/r/rust/

**Comment by mbrt** [comment]
Thanks! I've followed your suggestion:
http://redd.it/36z5mr
