### ISSUE TITLE
HashMap completion

### ISSUE THREAD

**Issue by aaronkavlie-wf** [phildawes/racer#246]
Racer can't complete `std::collections::HashMap`

**Comment by phildawes** [comment]
Wow, you're right. When did that stop working?! 
Thanks for the report, will look into this

**Comment by phildawes** [comment]
I think I see what's going on. Racer is completing std::collections to libcollections rather than the module in libstd/collections/. I guess
```extern crate collections as core_collections;``` is the line that's confusing it.

**Comment by phildawes** [comment]
Fixed now. Thanks for the report @aaronkavlie-wf
