### ISSUE TITLE
having trouble completing from cargo crates

### ISSUE THREAD

**Issue by tomjakubowski** [phildawes/racer#249]
Hi, first of all thanks so much for creating racer!

I'm trying to use racer from Emacs with a Cargo project. My understanding is that Cargo dependencies are now supported. However, I've been having trouble with it. As an example, I edited `src/main.rs` in the racer project itself, added `use toml::` to the top level scope of the file and asked Company for a completion. I got this:

```
Company: Back-end racer-company-complete error "/home/tom/.local/bin/racer exited with status 101" with args (candidates )
```

If I run `racer complete use toml::` from inside that `src` directory of my Racer repo I see nothing printed and racer exits with a 0 error code.

Completions for `std` all work just as one would expect, so I think that `RUST_SRC_PATH` is set up and racer is otherwise happy.

**Comment by phildawes** [comment]
Hi @tomjakubowski, What does your Cargo.toml look like?

**Comment by tomjakubowski** [comment]
Cargo.toml

```toml
[package]

name = "racer"
version = "0.0.1"
license = "MIT"
description = "Code completion for Rust"
authors = ["Phil Dawes <phil@phildawes.net>"]

[[bin]]
name = "racer"
path = "src/main.rs"

[profile.release]
debug = true

[dependencies]
log = "*"
syntex_syntax = "*"
toml = "*"

[features]
nightly = []
```

Cargo.lock
```toml
[root]
name = "racer"
version = "0.0.1"
dependencies = [
 "log 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "syntex_syntax 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "toml 0.1.20 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "bitflags"
version = "0.1.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "kernel32-sys"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "winapi 0.1.18 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "libc"
version = "0.1.8"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "log"
version = "0.3.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "libc 0.1.8 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "rustc-serialize"
version = "0.3.14"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "syntex_syntax"
version = "0.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "bitflags 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.1.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "rustc-serialize 0.3.14 (registry+https://github.com/rust-lang/crates.io-index)",
 "term 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)",
 "unicode-xid 0.0.1 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "term"
version = "0.2.7"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "kernel32-sys 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi 0.1.18 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "toml"
version = "0.1.20"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "rustc-serialize 0.3.14 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "unicode-xid"
version = "0.0.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "winapi"
version = "0.1.18"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "libc 0.1.8 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

**Comment by 4xrsJCr9** [comment]
Are you using `multirust` by any chance? If so, you'll need to symlink `~/.cargo` to `~/.multirust/toolchains/stable/cargo` or the like.

@phildawes: Perhaps the location of the cargo registry could be passed as an environment variable till https://github.com/rust-lang/cargo/issues/1098 is sorted out?

**Comment by phildawes** [comment]
@4xrsJCr9 yes that might be the easiest way. Or maybe racer should interrogate the .multirust directory to back out the directory. (i.e. look in .multirust/overrides and .multirust/default). 

(n.b. I'm not sure this is something a cargo lib can support easily without help from multirust)

**Comment by phildawes** [comment]
@tomjakubowski Is @4xrsJCr9 correct about multirust? (Completing toml::<tab> in the racer source works for me.) Thanks!

**Comment by tomjakubowski** [comment]
Yep, I've got multirust installed and that seems like a probable explanation. I'll give it a try with a workaround soon.

**Comment by phildawes** [comment]
I added some multirust support last night. It currently doesn't do overrides, but it should look in the current multirust 'default' cargo directory now. You have to delete your ~/.cargo dir for the new functionality to kick in. Hope this helps!
