### ISSUE TITLE
off by one bug

### ISSUE THREAD

**Issue by MarkSwanson** [phildawes/racer#250]
Given this snippet of code:

    let message = parser.errors.iter().map(|parser_error| {

$ ~/.vim/bundle/racer/target/debug/racer complete 192 63 src/lib.rs

PREFIX 52,63,parser_erro
CompletePath: contextstr is ||, searchstr is |parser_erro|
* Note the missing 'r' in 'parser_error'.

Patch to get the 'r' back:
```
diff --git a/src/main.rs b/src/main.rs
index 16cbd10..b28a978 100755
--- a/src/main.rs
+++ b/src/main.rs
@@ -73,10 +73,10 @@ fn complete(match_found: &Fn(Match)) {
             let src = racer::load_file(&fpath);
             let line = &*getline(&fpath, linenum);
             let (start, pos) = racer::util::expand_ident(line, charnum);
-            println!("PREFIX {},{},{}", start, pos, &line[start..pos]);
+            println!("PREFIX {},{},{}", start, pos, &line[start..pos+1]);

             let point = scopes::coords_to_point(&*src, linenum, charnum);
-            for m in racer::complete_from_file(&*src, &fpath, point) {
+            for m in racer::complete_from_file(&*src, &fpath, point+1) {
                 match_found(m);
             }
         }
```
I now get:

PREFIX 52,63,parser_error
CompletePath: contextstr is ||, searchstr is |parser_error|
resolve_path P[parser_error] Some("src/lib.rs") 7016 StartsWith
resolve_name parser_error Some("src/lib.rs") 7016 StartsWith BothNamespaces
search_local_scopes PathSegment { name: "parser_error", types: [] } Some("src/lib.rs") 7016 StartsWith BothNamespaces
searching scope BothNamespaces start: 6951 point: 7016 'parser_error' Some("src/lib.rs") StartsWith local: true
search_scope found matches StartsWith []
search_scope_headers for |parser_error| pt: 6950
PHIL search_scope_headers preblock is |let message = parser.errors.iter().map(|parser_error| |
searching scope BothNamespaces start: 6883 point: 7016 'parser_error' Some("src/lib.rs") StartsWith local: true
...

I'm not sure how much this helps. It didn't help racer find the type of parser_error.

I briefly analyzed the rustc ast-json output and  saw parser_error was defined as a node.
This seemed positive because the ast should then contain a mapping to the inferred return type of parser_error.
But I see types: [] -> which doesn't seem helpful :-)

The ast visitor doesn't seem to be getting used?
Maybe resolve_name() could search the AST after search_local_scopes() ?
I'm still hoping the AST has the type...

**Comment by phildawes** [comment]
Hi Mark,

Thanks for the issue. Just so I understand: In your example the column 63 isn't in the snippet you posted. (the snippet is only 55 chars long). Is your cursor over the 'r' character when you complete? (char 51)

Regardless, I'm afraid racer cannot currently derive the types of lambda parameters. I am working on a version of racer that uses rustc internals to derive the types of expressions, which should make this possible but is a little while off yet.

**Comment by MarkSwanson** [comment]
Hmm... I can't find my test code...
I'm sure my cursor was over one of the characters in "parser_error".

Wrt deriving types: ok, waiting patiently.
