### ISSUE TITLE
Explicit check for "src" in RUST_SRC_PATH breaks indirection

### ISSUE THREAD

**Issue by jonhoo** [phildawes/racer#253]
racer currently checks that `RUST_SRC_PATH` [ends with "src"](https://github.com/phildawes/racer/blob/849b08788a32abff3e2591ed62d5dc8435de9f9d/src/main.rs#L158). Unfortunately, this means that indirection (like symlinks) cannot be used to maintain a version-independent link to the Rust sourcer. For example, I have the Rust sources in `~/src/rust/src/rustc-1.0.0/src`, but would prefer not to hard-code that path in my `.vimrc`. Instead, I do:

    ln -s ~/src/rust/src/rustc-1.0.0/src ~/.rust-src

And set `RUST_SRC_PATH=~/.rust-src` in my `.vimrc`. Unfortunately, the aforementioned "ends with src" check comes back to bite me here, and gives me the error:

> `RUST_SRC_PATH` variable needs to point to the *src* directory inside a rust checkout e.g. `"/home/foouser/src/rust/src"`.

Can this be removed, or replaced with a more appropriate check? For example, checking that `RUST_SRC_PATH` points to a directory that contains `libstd/`, or one that *doesn't* contain `src/`, might be a better alternative..

**Comment by jonhoo** [comment]
FWIW, a workaround is to do

    mkdir ~/.rust
    ln -s ~/src/rust/src/rustc-1.0.0/src ~/.rust/src

**Comment by phildawes** [comment]
Hi @jonhoo. I like the libstd idea, I'll change racer to do that one tonight
