### ISSUE TITLE
No method signatures in vim

### ISSUE THREAD

**Issue by jonhoo** [phildawes/racer#254]
With `completeopt=menu,preview`, the completion popup does not show method signatures that can be seen in the screenshots you've [posted elsewhere](http://phildawes.net/blog/2014/08/21/racer-update3/). AFAICT, you're using emacs, so presumably this is a vim-specific issue... Is this expected behaviour, or is it a bug?

![vim screenshot showing no method signatures in completion dialog](https://jon.tsp.io/share/racer-vim-no-signatures.png)

**Comment by phildawes** [comment]
Hi @jonhoo. I think your vim plugin is behaving as expected. IIRC there is a way to turn on the extra completions - I think by setting the flag  g:racer_experimental_completer. I didn't write this feature though, so your best bet is to look at the vim plugin code.
Cheers,
Phil

**Comment by jonhoo** [comment]
Well, `let g:racer_experimental_completer = 1` shows a single-letter suffix (`s` for structs, `f` for function, etc.), but won't give full method signatures (which vim is capable of showing). In fact, that current vim code shortens the extra information on purpose, though I have no idea why.

I might take a look at this myself at some point, but for the moment, I don't think this ticket should be closed. This is indeed a shortcoming of the current vim plugin, and it is not fixed.

**Comment by jonhoo** [comment]
Hum, the problem just magically resolved itself for me after a plugin update. Can't see anything that would cause this. I now get full method signatures in the dropdown :/
