### ISSUE TITLE
Racer not working within Vim

### ISSUE THREAD

**Issue by gaveen** [phildawes/racer#255]
**Env**
Vim: 7.4 (with Vundle)
OS: Fedora 20 (x86_64) Linux
Racer: git head (f2f890990cae6b4f051cb69c0bd18bb256579e61)
Rust: 1.0.0

**Config snippets**
[.vimrc]
let g:racer_cmd = "bundle/plugin-racer/target/release/racer"
let $RUST_SRC_PATH="/home/xxxxxx/Software/builds/rust/rust-1.0.0/src"

[.bash_profile]
export RUST_SRC_PATH=$HOME/Software/builds/rust/rust-1.0.0/src

**Description**
I have everything configured as instructed in the _README_. Racer works as expected in the command line, but fails to provide any completion inside Vim.

**Expected behaviour**
Enter a partial statement and in Inset mode, press C-x-C-o. Auto-complete suggestions should be listed.

**Observed behaviour**
Vim shows no startup errors related to plugin configuration. When trying to auto-complete with C-x-C-o, I get the error message:
"-- Omni completion (^O^N^P) Pattern not found"

**Further details**
Omni-completion related config in .vimrc:
setlocal ofu=syntaxcomplete#Complete
set completeopt-=preview
Disabling these didn't help either.

**Comment by aminb** [comment]
I think [rust-lang/rust.vim](https://github.com/rust-lang/rust.vim) is required (for actually detecting rust files).

IIRC I had this exact problem and I installed rust.vim and it's been working since.

**Comment by yeahnoob** [comment]
@gaveen As you said `let g:racer_cmd = "bundle/plugin-racer/target/release/racer"`, did you try to replace it with `let g:racer_cmd = "/home/xxxx/.vim/bundle/xxx/xxx/target/release/racer"` ??
And check that the ex-file racer is in the right path.
PS. The Racer Plugin works fine in my Vim.(including neocomplete.vim)

**Comment by gaveen** [comment]
@aminb I already had rust.vim in place.

@yeahnoob the executable racer was in the right place all right. Changing
`let g:racer_cmd = "bundle/plugin-racer/target/release/racer"` into
`let g:racer_cmd = "/home/xxxxxx/.vim/bundle/plugin-racer/target/release/racer"` fixes this. 

So the completion works now, but I'm not overjoyed about having to hardcode the path in my vimrc. Something I failed to mention in my initial report is that my `~/.vim` and `~/.vimrc` are symlinks to somewhere else. So this maybe a factor in the problem. After a brief glance into racer.vim, I'm not sure if this is about how the executable is invoked or built. I'm quite new to Rust.

So shall we call @yeahnoob's tip a workaround, and try to figure what's happening before closing this ticket? Please let me know how I can help.

**Comment by phildawes** [comment]
Hi @gaveen. If I understand correctly it sounds like this is working correctly as documented.
Is the issue that you want the vim plugin to be able to run the racer binary using a relative path, but you don't know how that works in vim?

**Comment by gaveen** [comment]
@phildawes Well, it's working when I use the absolute path. But I couldn't get it working with a relative path (perhaps owing to my symlinked vim files). It would be much nicer to be able to use a relative path. If the absolute path is always assumed, perhaps it's better to have the README updated as well?

**Comment by phildawes** [comment]
Hi @gaveen. I'm afraid I'm going to close this because I'm not going to work on it myself and it seems like it might be a vim issue (maybe with symlinked files) rather than a racer bug. Feel free to open a more specific issue if you still think it's a racer bug, Thanks!
