### ISSUE TITLE
Sensible default values for racer.el defvars

### ISSUE THREAD

**Issue by moonlite** [phildawes/racer#261]
It would make sense to me to let `racer-cmd` default to whatever `racer` command is available in the `PATH` if not set and to make `racer-rust-src-path` default to the env variable `RUST_SRC_PATH` if not set.

Thanks for a great project all in all! :)

**Comment by phildawes** [comment]
Hi @moonlite ! I think it already does the latter (RUST_SRC_PATH), but it doesn't do the former and that does seem like a good idea. Patches welcome!

**Comment by moonlite** [comment]
Fixed by #294.
