### ISSUE TITLE
Can't build the source on my Debian box

### ISSUE THREAD

**Issue by kenshinji** [phildawes/racer#276]
After I issuing 'cargo build --release', I got this error information

Could not compile `syntex_syntax`.

Caused by:
  Process didn't exit successfully: `rustc /home/kenshinji/.cargo/registry/src/github.com-1285ae84e5963aae/syntex_syntax-0.7.0/src/lib.rs --crate-name syntex_syntax --crate-type lib -C opt-level=3 -g -C metadata=1313b583a9caa89d -C extra-filename=-1313b583a9caa89d --out-dir /home/kenshinji/git/racer/target/release/deps --emit=dep-info,link -L dependency=/home/kenshinji/git/racer/target/release/deps -L dependency=/home/kenshinji/git/racer/target/release/deps --extern rustc_serialize=/home/kenshinji/git/racer/target/release/deps/librustc_serialize-5f72ca5317ec3df9.rlib --extern term=/home/kenshinji/git/racer/target/release/deps/libterm-4982b09cb1e4ce16.rlib --extern log=/home/kenshinji/git/racer/target/release/deps/liblog-3bd4262ed276ddcd.rlib --extern libc=/home/kenshinji/git/racer/target/release/deps/liblibc-38eabbf337f9ec62.rlib --extern unicode_xid=/home/kenshinji/git/racer/target/release/deps/libunicode_xid-5cd2288717185853.rlib --extern bitflags=/home/kenshinji/git/racer/target/release/deps/libbitflags-17ef4b05257c24e8.rlib -Awarnings` (signal: 9)

My Debian version is as following:

kenshinji@DebianBox:~/git/racer$ cat /etc/issue
Debian GNU/Linux 7.0 \n \l

**Comment by phildawes** [comment]
Hi @kenshinji 
Which version of rust are you using?

**Comment by kenshinji** [comment]
I installed rust runtime on my VPS via the following command:
`$ curl -sf -L https://static.rust-lang.org/rustup.sh | sh`
So I think it should be version 1.0, I don't know how to check the rust runtime from console though.
And I compiled it successfully on my laptop, which is running Ubuntu 14. Is this because of less memory on my VPS? It only has 512 MB memory. 
PS: racer runs perfectly on my Macbook Pro. :smile:

**Comment by andoriyu** [comment]
@kenshinji just run into the same issue. If you look at `top` during `cargo build` you would see that you running out of memory and majority of time spent in swap.

**Comment by kenshinji** [comment]
@andoriyu yup, I see, the rustc process was eating more and more memory, then it got killed by system.
I guess this is the root cause of this issue, is there a way that we can avoid it being killed by system? Or saying, can we specify a total memory usage of rustc?

**Comment by andoriyu** [comment]
@kenshinji you can try adding more swap space, but this will make compilation process slow af and still might fail. When I had to compile gcc5 on my VPS I had to temporally use bigger instance, that be the easiest way besides asking someone for compiled binary. I only have binary for freebsd which won't work on linux.
