### ISSUE TITLE
update racer in crates.io

### ISSUE THREAD

**Issue by gozes** [phildawes/racer#285]
is there any particular reason why racer hasn't been updated in crates.io so that it can be installed by cargo?

**Comment by phildawes** [comment]
Hi Gozes,
Racer only added a working library interface in the last week or so (thanks @Victor-Savu!), and it's pretty early support so I haven't released a cargo package yet. Are you planning to build against the library?

**Comment by gozes** [comment]
@phildawes not really I am just trying to figure out how to setup racer properly. for example, for RUST_SRC_PATH do I need clone the rust src from github and set the path to it or can I use the path where libstd-rust-dev(/usr/lib/rustlib) was install on  debia or where it gets install on arch linux?

**Comment by phildawes** [comment]
Hi @gozes 
You need to clone the rust src for github, or download it from here: http://www.rust-lang.org/install.html

**Comment by phildawes** [comment]
btw, I think you've got the wrong idea about crates.io: Packages there aren't binaries for install, rather they are rust libraries for other rust programs to use. Racer is currently a binary package (editors/ides invoke it by running the process) which is why the version there isn't up to date. Hope that makes sense

**Comment by PeterBocan** [comment]
Hello guys, I do wonder, if you talk about this strange error:

    Downloading term v0.2.11
    Unable to get packages from source

    Caused by:
    Failed to download package `term v0.2.11` from https://crates.io/api/v1/crates/term/0.2.11/download
    
    Caused by:
            SSL peer certificate or SSH remote key was not OK

I tried to install/build Racer for Vim (`cargo build --release`) ... and ideas what to do?

**Comment by phildawes** [comment]
Hi Peter,

I just cleared my cargo registry and tried to compile and this is working
fine for me. (Cargo downloads term v0.2.11 fine).
Is this still broken for you? Are you behind a firewall or something?

Cheers,

Phil

**Comment by PeterBocan** [comment]
I'm just behind my router's firewall. I'm running on OS X and trying to build Racer for Neovim support.

**Comment by phildawes** [comment]
Which version of rust/cargo are you using?

**Comment by PeterBocan** [comment]
cargo 0.2.0-nightly (a483581 2015-05-14) (built 2015-05-15)
    rustc 1.1.0 (35ceea399 2015-06-19)

**Comment by denis631** [comment]
Hi Phil, 
I'm experiencing the same problem as Peter. I've turned off the Firewall, but it didn't work out.

cargo 0.4.0-nightly (15b497b 2015-07-08) (built 2015-07-09)
rustc 1.2.0 (082e47636 2015-08-03)

Any suggestions ?

**Comment by PeterBocan** [comment]
I've solved it somehow. I had to reinstall rust with cargo.

**Comment by denis631** [comment]
I guess the problem is in cargo, since it points to the invalid links...
I've installed openssl from brew. Installed nighty version of rustc. Didn't work out.
