### ISSUE TITLE
Problems installing on OSX

### ISSUE THREAD

**Issue by franleplant** [phildawes/racer#288]
Hi!
    I've built the source without a problem but I don't have `rust/src` anywhere. I installed rust via the OS official installer.

Any clues?

Thanks!
Fran

**Comment by phildawes** [comment]
Hi @franleplant 
I'm afraid the rust installers don't come with source, you must download it separately. E.g. here: http://www.rust-lang.org/install.html

**Comment by franleplant** [comment]
Sorry for the late response, I was out of the country.

So I did download the rust src manually and did all the configuration steps, but when I try to use it with VIM it tells me `"-- Omni completion (^O^N^P) Pattern not found"`

I found this other issue https://github.com/phildawes/racer/issues/255 which seems related, I tried the things suggested there and I couldnt make it work.

I wont have much time to provide feedback but Ill do my best, thank you a lot for your work.
