### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Yamakaky** [phildawes/racer#292]
Did you consider implementing [this](http://keepachangelog.com/) ?

**Comment by phildawes** [comment]
Yeah, that's a good idea. Racer hasn't really had any releases and so I've been documenting news and changes in my blog: http://phildawes.net/blog/tag/racer/

But you're right, racer would probably benefit from a changelog

**Comment by Yamakaky** [comment]
It seems to work pretty well, so maybe you should tag it 0.1 or 1.0 ?

**Comment by phildawes** [comment]
Yes, I think maybe you're right. Will think about tagging it some time this week
