### ISSUE TITLE
Racer breaks emacs region indentation

### ISSUE THREAD

**Issue by gsingh93** [phildawes/racer#296]
I'm not 100% sure this is an issue with racer, but ever since enabling it, when I hit tab after selecting a region, nothing happens. I have to indent each line individually.

**Comment by phildawes** [comment]
Thanks for the bug report: Yep, this sounds like racer's fault for overriding tab. I wonder what the best fix for it is...?

**Comment by gsingh93** [comment]
I don't know much about emacs dev, but it looks like you're currently using `indent-according-to-mode` to indent. The documentation for this only refers to indenting lines, not regions.

When I check what my tab does by default, it runs `indent-tab-for-command` (although I don't know if that's the default or one my many configurations changed it). The documentation for this command refers to indenting both regions and lines. Maybe this should be used instead?

**Comment by gsingh93** [comment]
@phildawes I just tested this and making the change described above fixes the problem. Will you accept a PR with this change (or you can make it yourself if you have the time, doesn't matter to me)?

**Comment by phildawes** [comment]
Hi @gsingh93. 
I tried substituting 'indent-tab-for-command', but I get: ```Symbol's definition is void: indent-tab-for-command```
Do you know if this works on a vanilla emacs with no modifications?

**Comment by gsingh93** [comment]
Strange, it should be built in:
http://www.gnu.org/software/emacs/manual/html_node/elisp/Mode_002dSpecific-Indent.html

**Comment by phildawes** [comment]
Maybe a recent addition? I'm on emacs 24.3.1

**Comment by gsingh93** [comment]
Oops, I typed it wrong. It's `indent-for-tab-command`, not `indent-tab-for-command`.

**Comment by phildawes** [comment]
Oh cool. Will try this out tonight and make the change if it works.
Thanks v much

**Comment by phildawes** [comment]
Done. Thanks again @gsingh93 !
