### ISSUE TITLE
unable to compile kernel32-sys on windows7 64-bit

### ISSUE THREAD

**Issue by abbychau** [phildawes/racer#297]
![screenshot](https://cloud.githubusercontent.com/assets/350283/8507647/4e9bad72-227e-11e5-98a3-73892fe2ecac.png)

D:\DEVELOPMENT\racer-master>D:\Rust1.1\bin\cargo.exe build --release
   Compiling kernel32-sys v0.1.2
failed to run custom build command for `kernel32-sys v0.1.2`
Process didn't exit successfully: `D:\DEVELOPMENT\racer-master\target\release\bu
ild\kernel32-sys-4b26f914b467c779\build-script-build` (exit code: -1073741515)

**Comment by phildawes** [comment]
@jaxx just upgraded the version info. Could you give it another go?
Which version of rust are you using?

**Comment by phildawes** [comment]
Closing. Please reopen if this is still an issue.
-Thanks!

**Comment by globin** [comment]
Have this issue with Windows 10 64-bit:

```
Compiling winapi v0.2.2 (file:///F:/dev/winapi-rs/lib/kernel32-sys)
Compiling winapi-build v0.1.1 (file:///F:/dev/winapi-rs/lib/kernel32-sys)
Compiling kernel32-sys v0.1.4 (file:///F:/dev/winapi-rs/lib/kernel32-sys)
Build failed, waiting for other jobs to finish...
failed to run custom build command for `kernel32-sys v0.1.4 (file:///F:/dev/winapi-rs/lib/kernel32-sys)`
Process didn't exit successfully: `F:\dev\winapi-rs\lib\kernel32-sys\target\debug\build\kernel32-sys-8e0909f63b633aae\build-script-build` (exit code: -1073741515)
```

**Comment by phildawes** [comment]
Hi Robin,
I'm not sure. Maybe delete the Cargo.lock file and retry (this will make it
download the latest version of kernel32-sys).
What version of rust and racer are you using?

**Comment by apthorpe** [comment]
I had a similar problem with kernel32-sys v0.1.4 not building, failing with a "std-198068b3.dll is missing" message on Windows 8.1 (screenshot attached). On a hunch, I reviewed my PATH setting, and removed the entry for "C:\TDM-GCC-64\bin", cleaned and rebuilt. Once the conflicting installation of gcc was out of the way, kernel32-sys built. Check for stray installations of gcc, ld, cygwin and the like.

The build later got hung up on syntex_syntax v0.16.0, but that's a separate issue...

![kernel32-sys_failure](https://cloud.githubusercontent.com/assets/1111821/10271293/d081168e-6ad0-11e5-9f6f-64c0a8ac9dcb.png)
