### ISSUE TITLE
Unable to build on Windows 64-bit

### ISSUE THREAD

**Issue by synkarius** [phildawes/racer#302]
I downloaded source, checked "add to path", then ran "cargo build --release". No idea what's wrong here.

	C:\Users\dave\Desktop\racer-master>C:\Program Files\Rust beta 1.0\bin\cargo buil
	d --release
	'C:\Program' is not recognized as an internal or external command,
	operable program or batch file.

	C:\Users\dave\Desktop\racer-master>"C:\Program Files\Rust beta 1.0\bin\cargo" bu
	ild --release
	   Compiling bitflags v0.3.0
	   Compiling rustc-serialize v0.3.15
	   Compiling regex-syntax v0.1.2
	   Compiling winapi-build v0.1.0
	   Compiling libc v0.1.8
	C:\Users\dave\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-serialize-0.
	3.15\src\serialize.rs:441:24: 441:31 error: use of undeclared trait name `ToOwne
	d`
	C:\Users\dave\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-serialize-0.
	3.15\src\serialize.rs:441 impl<'a, T:Encodable + ToOwned + ?Sized> Encodable for
	 Cow<'a, T> {

													 ^~~~~~~
	C:\Users\dave\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-serialize-0.
	3.15\src\serialize.rs:449:14: 449:21 error: use of undeclared trait name `ToOwne
	d`
	C:\Users\dave\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-serialize-0.
	3.15\src\serialize.rs:449     where T: ToOwned, T::Owned: Decodable

										   ^~~~~~~
	error: aborting due to 2 previous errors
	   Compiling unicode-xid v0.0.1
	Build failed, waiting for other jobs to finish...

**Comment by phildawes** [comment]
It looks like rust-serialize is failing to build. Which rust version are you running against?

You could try deleting Cargo.lock and seeing if it will build without locked versions

**Comment by synkarius** [comment]
At first, I tried running with 1.1.0. Then I read somewhere that I shouldn't be using that version. So I uninstalled, and installed 1.0.0. I tried deleting Cargo.lock, but it didn't help. The file was re-created, and I got the same error. Should I be in the src/racer folder or the folder that contains Cargo.lock? I tried from both.

**Comment by phildawes** [comment]
Oh that sucks. Sorry you're having so much trouble. Are you on the latest racer master?
I'm afraid I don't have a windows box to try to reproduce this on at the moment. I will try to get access to one.

**Comment by synkarius** [comment]
Yes, latest master as of time of writing this. (I tried it again from scratch.) Here are my exact steps:

1. Install rust-1.0.0-beta-x86_64-pc-windows-gnu.msi, selecting "add to path" from options
2. Download racer by clicking "download zip" from racer Github
3. Extract and navigate to racer-master/src/racer
4. Type "cargo build --release" sans quotes

**Comment by synkarius** [comment]
Also possibly worth mentioning, if I keep running "cargo build --release", it gets to a different error:

    Could not compile 'aho-corasick'.

**Comment by phildawes** [comment]
Hi @synkarius,
rust-1.0.0-beta-x86_64-pc-windows-gnu.msi sounds very old (was pre-1.0). Do you get any joy with e.g. 1.1 stable from here: http://www.rust-lang.org/install.html ?

**Comment by razvan-panda** [comment]
I got a similar error on first build. After deleting the lock file and building again it worked without any errors. Also using rustc 1.1.0.

**Comment by synkarius** [comment]
It compiles! I could have sworn I tried with 1.1.0 before. I had the installer downloaded. Could I have uninstalled 1.0.0 and reinstalled it, thinking it was 1.1.0? Whatever.

Thank you for your help.
