### ISSUE TITLE
Is source-based completion really needed?

### ISSUE THREAD

**Issue by SoniEx2** [phildawes/racer#306]
Can't you do rlib-based completion or something instead?

**Comment by kornholi** [comment]
You need source completion for the current crate but the rlib metadata should have everything you need for library code. Hopefully more areas of rustc become reusable soon.

**Comment by phildawes** [comment]
Hi @SoniEx2, yes rlib based completion is possible. I am working on getting completion with rustc fast enough to use in racer.

**Comment by SoniEx2** [comment]
Well can you make it take a RUST_LIB_DIR or something instead of the rust sources? Would make my life easier.

For the current crate on the other hand, do w/e you want, I don't mind.

**Comment by phildawes** [comment]
Yes, will do RUST_LIB_DIR at some point, but this is a way off at the
moment.
