### ISSUE TITLE
Crashes on super:: type completions

### ISSUE THREAD

**Issue by fkaa** [phildawes/racer#308]
Crashes when trying to complete said types. Test case:

```rust
// src/lib.rs

pub enum Foo {
    Bar
}
```

```rust
// src/quux/mod.rs

use super::Foo;

#[test]
fn crashy_crashy() {
     // try and complete the type    
     // let a = F
}
```

**Comment by phildawes** [comment]
Thanks @fkaa. It looks like you don't even need the lib.rs, the mod.rs file on it's own is enough to send it into infinite recursion. Will try and look at fixing this tonight

**Comment by fkaa** [comment]
@phildawes just came across another similar behavior, `::` inside parens seem to crash:
```
enum Foo {
    Bar(i32)
}

#[test]
fn crashy_crashy() {
    let a = Foo::Bar(/*:: typing this crashes*/);
}
```

**Comment by phildawes** [comment]
Hi @fkaa 
I think this is fixed in master now. Reopen if not.
Thanks again for raising this!
-Phil
