### ISSUE TITLE
cannot complete at alias' dot subscript

### ISSUE THREAD

**Issue by Congee** [phildawes/racer#311]
Just came across this when trying completing at the dot.
Would you guys tell me if racer just doesn't funciton well or racer inherently cannot implement this kind of completion?
:D

``` rust
pub fn main() {
    struct Point {x: i32, y: i32}

    let mut point = Point { x: 1, y: 2 };
    let borrowed_point = &point;
    borrowed_point.
}
```
``` bash
CC@racer $ RUST_SRC_PATH=~/src/rust/rust/src ./target/release/racer complete 6 19 borrowed_point. test.rs
PREFIX 19,19,
- Could not match expr node type: ExprAddrOf(MutImmutable, expr(4294967295: point))
```

**Comment by phildawes** [comment]
Thanks for the report @Congee, you're right, racer isn't matching this. Looks like an easy fix, I'll try and get to it tonight.

**Comment by Congee** [comment]
It works greatly. Thanks for your fi. ;D
