### ISSUE TITLE
Racer crashes when referencing an external package in emacs

### ISSUE THREAD

**Issue by liamoc** [phildawes/racer#315]
I made a simple example crate using the sdl2 library from crates.io. I think I set up racer correctly, and completion works when I type "std::io::B" inside the emacs buffer, but if I try and use an external package, (e.g, type "sdl2::I") I get the following error message in the emacs message buffer:

    deferred error : (error "Process [/Users/liamoc/.rust/racer] exited abnormally : PREFIX 9,9,
    thread '<main>' panicked at 'position 0 does not resolve to a source location', /Users/liamoc/.cargo/registry/src/github.com-0a35038f75765ae4/syntex_syntax-0.8.0/src/codemap.rs:912
    ")

I am using OS X, with Spacemacs (emacs 24.4.1), if that helps.

**Comment by liamoc** [comment]
Hm, I explicitly installed the racer package, and it works now except the message still shows.

**Comment by gozes** [comment]
@liamoc  the racer package is really out of date and I think it has ever been updated. why it is that way  I don't know

**Comment by liamoc** [comment]
Right, the completion (and the error) I'm getting is coming from the company-racer package.

**Comment by phildawes** [comment]
(I think @gozes is referring to the crates.io package racer package being out of date. This isn't used by emacs)
