### ISSUE TITLE
Question about deamon mode.

### ISSUE THREAD

**Issue by bruno-medeiros** [phildawes/racer#322]
I just noticed by chance the new Racer has a new deamon mode.

Is this mode recommended over the previous modes? For example, are there possible performance enhancements (AST caching, etc.) ? If so, is there anything special I'd need to know to integrate this mode into an IDE. I tried it out and it seems to accept the same commands as the command-line

**Comment by phildawes** [comment]
Currently there's no real advantage to using this mode. I added it because I plan to work on tighter support with the rust compiler, and for that racer will likely need to hold and cache state.

**Comment by bruno-medeiros** [comment]
Yeah, such evolution would require a resident process.

Well, now that you have a Changelog, it would be most suitable if any future protocol changes be documented there.
