### ISSUE TITLE
Panic on colon : 

### ISSUE THREAD

**Issue by JoshBlake** [phildawes/racer#327]
I'm using Atom and atom-racer on Windows 8.1 x64, which recently has been telling me that racer exited with code 101. This is with racer tag v1.0.0. I have narrowed down this issue to racer itself (outside of atom/atom-racer) with this file:

```
struct Foo {
    value : i32,
}

fn bar(data : u8) { }
```
Save that as main.rs, then call racer. Both of these lines cause a racer panic:
```
racer.exe complete 2 11 /path/to/main.rs
racer.exe complete 5 13 /path/to/main.rs
```
Output:
```
PREFIX 11,11,
thread '<main>' panicked at 'index 0 and/or 18446744073709551615 in `:` do not lie on character boun
dary', ../src/libcore\str/mod.rs:1284
```

The 2:11 and 5:13 are both on the colon separating the field/parameter and its type.
I had this happen with Rust 1.2 beta and now Rust 1.3 beta.
It is distracting when using racer in an IDE because racer invocations seems to crash randomly when typing code.

**Comment by phildawes** [comment]
Thanks for filing the issue Joshua, I'll take a look

**Comment by JoshBlake** [comment]
Great, thanks!
