### ISSUE TITLE
Can't show methods of String in "libcollections\str.rs"

### ISSUE THREAD

**Issue by varding** [phildawes/racer#328]
Race only show methods of String in "libcollections\string.rs" but none in "libcollections\str.rs"

The code below only show "truncate" but not include the method "trim" of &str

let mut s = String::new();
s.tr

platform:win7 x64
rust 1.2.0 stable

**Comment by varding** [comment]
![image](https://cloud.githubusercontent.com/assets/4688041/9188469/0671f6f6-400f-11e5-96ce-90907cdda811.png)

The method "trim" of str that I want to display was not there.

**Comment by phildawes** [comment]
Hi Varding,

Thanks for the issue, I'll take a look, possibly this evening

**Comment by Rodney-Gabriel** [comment]
@phildawes is there anywhere online is there tutorials to show a newbie how to install racer? Im not familiar with the terminal and I really like what racer is purported to do. As a newbie any feature that can cut time can give me more time to study and learn the Rust language. Im trying to install it for use in ATOM and have no clue what i'm doing. Im on mac OS X 10.10.3

**Comment by phildawes** [comment]
@Rodney-Gabriel. I'm afraid being familiar with your environment (e.g. the terminal, your editor) is pretty-much a prerequisite for using rust/racer, as I don't have the available time/manpower to orient instructions to an absolute beginner, sorry.

**Comment by phildawes** [comment]
Hi @varding, Thanks for the issue. I'm afraid resolving &str methods for String requires racer being able to follow deref-coercions. I've opened #334 for this enhancement.

**Comment by varding** [comment]
@phildawes 
Great! Thank you for your hard work on Racer!!
