### ISSUE TITLE
Make a Vim variable that allows users to set the path of the tmp file

### ISSUE THREAD

**Issue by stratact** [phildawes/racer#330]
I would like to be able to override the path of where the racertmp files get written.

E.g. Instead of the current directory, a user could point to `/tmp` as the default

**Comment by phildawes** [comment]
The racer binary can support this (thanks to #278, thanks @damienrg), so all that is needed is to have .vim send the temporary filename as an additional argument to racer. Does anybody with vim experience fancy adding this?

**Comment by lilydjwg** [comment]
It's great that racer now supports this., but recently I might not have the time to do it...

**Comment by Shougo** [comment]
OK.  I can do it.

**Comment by Shougo** [comment]
Fixed the problem.
