### ISSUE TITLE
Panic on file with 1 character, or out of range line:column

### ISSUE THREAD

**Issue by JoshBlake** [phildawes/racer#331]
Tested with 7ae984f5f
```
$ echo "m" > test.rs
$ racer complete 1 1 test.rs
thread '<main>' panicked at 'assertion failed: index.end <= self.len()', ../src/libcore\slice.rs:572
```
Interestingly, if I do:
```
$ echo " m" > test.rs
```
then complete with 1 1, 1 2, or 1 3, it is ok (but no results). But 1 4 panics.

Same panic if the line number is past the end of the file.

Not sure if line and column are supposed to be 0 or 1 based. I think 1 based, but providing 0 for line or column produce interesting results:
| File  | Line | Column | Results |
|-------|--------|------------|-----------|
| "m"  | 0      | 0            |   panic |
| "m"  | 0      | 1            |   panic |
| "m"  | 1      | 0            |   panic |
| " m" | 0      | 0            |        ok |
| " m" | 0      | 1            |   panic |
| " m" | 1      | 0            |        ok |

**Comment by phildawes** [comment]
Thanks for the issue, I'll check it out (hopefully today)

**Comment by phildawes** [comment]
This turned out to be an out of bounds error when testing for the BOF unicode header (present in some windows text files). Thanks for reporting the issue @JoshBlake
