### ISSUE TITLE
Don't remove other company modes

### ISSUE THREAD

**Issue by gsingh93** [phildawes/racer#339]
The emacs mode sets the `company-backends` variable to be just `(racer-company-complete)`:
```
(set (make-local-variable 'company-backends) '(racer-company-complete))
```

It should instead add this function to the list, so the other modes aren't overwritten. I find `company-dabbrev-code` to be a useful backend, and it's annoying to have to renable it with racer installed.

**Comment by dleslie** [comment]
It's my understanding that the general convention for company backends is to instruct the user to install them by:

```elisp
(add-to-list 'company-backends 'company-new-backend)
```

Even the name ```racer-company-complete``` is out of step with the general naming convention for new company backends.

**Comment by dleslie** [comment]
Likewise, there's no need to make ```'company-backends``` into a local variable.

**Comment by gsingh93** [comment]
@dleslie Agreed on all points. I think the automatic installation of the company mode backend should be removed, `racer-company-complete` should be renamed to `company-racer`, and a description of how to add this backend added to the README.

Once this is done, if all the functionality from [company-racer](https://github.com/emacs-pe/company-racer) mode is implemented in `racer-mode`, we also might want to ask the developer to remove his project from melpa. I was confused when I saw that, I wasn't sure if it was by the developers of racer or not.

**Comment by Wilfred** [comment]
All that `racer-activate` does is set `company-backends` for the current buffer. It provides a simple way of getting up and running, but it's optional.

Agreed that `company-racer` would be a better name, sadly that project already exists. racer.el also provides eldoc and jumping to definition, so perhaps the current name is better -- it's not just company integration.

**Comment by gsingh93** [comment]
@Wilfred The README should specify that `(racer-activate)` is optional then. And regardless of whether it is or isn't optional, it should add a backend rather then set a single backend.

Racer provides features other than company integration, but we're saying the company backend function is improperly named, not the project itself. We may not be able to take `company-racer` (but we should seriously ask that project maintainer if we can first), but we should definitely prefix the backend function with `company-`. Even `company-racer-backend` or `company-racer-complete` would be better than the current name.

**Comment by tomjakubowski** [comment]
FWIW CIDER, which is analogous in some ways to Racer, includes support for company-mode out of the box, and auto-complete-mode through a companion library. https://github.com/clojure-emacs/cider

Of interest is the section of their README on integrating with Company. https://github.com/clojure-emacs/cider#auto-completion
