### ISSUE TITLE
vim: Allow opening definition in new split-window

### ISSUE THREAD

**Issue by marcianx** [phildawes/racer#342]
It would be nice to have, eg, gD open the definition in a new split-window, after which one could use gd to explore further within that window.

**Comment by phildawes** [comment]
I don't use vim personally, but I'd be open to merging such a patch unless somebody else disagrees.

**Comment by jwilm** [comment]
@phildawes looks like this has been resolved

**Comment by MattWis** [comment]
Can confirm, this should have been closed when my PR was merged in
