### ISSUE TITLE
Racer Emacs support needs a better maintainer(s)

### ISSUE THREAD

**Issue by phildawes** [phildawes/racer#343]
@Wilfred, @freebroccolo, @tomjakubowski, @moonlite, @marvelm, @ane
(sorry if I missed anybody)

It's pretty obvious that I'm not the best equipped to maintain the racer emacs stuff, most of the code is from other contributors. Does anybody(s) fancy taking over maintenance of the emacs bindings?

Also now that racer-emacs support is in melba the code could be moved to a separate github project. I am squatting the 'rust-racer' github organisation, (https://github.com/rust-racer/) so maybe we could create a separate project in there?

Any thoughts? Thanks!

**Comment by Shougo** [comment]
I think Vim support maintainers are also needed....

**Comment by damienrg** [comment]
It may also be good to have a racer package with no dependency on completion system (auto-complete, company, ...) as mentioned by @marsam in https://github.com/phildawes/racer/pull/252#issuecomment-109821276.

**Comment by marvelm** [comment]
If `racer` is going to be spun out into a repository, I think we should consider using an IRC channel to cut down on the number of support-related issues. I've been sitting in #racer on moznet for a while. I've just registered the channel today, and I can transfer ownership.

**Comment by Wilfred** [comment]
On the contrary, I think you're doing a great job @phildawes! You've created a successful project with contributions from lots of different people. If you'd like others to review/merge Emacs related pull requests, you could give some Emacs folks commit access to this repo? I'd be happy to help.

As for splitting out racer.el, I don't feel strongly. Separate repos allow separate READMEs with appropriate instructions for the relevant tool. A combined repo allows the editor integration to evolve with racer itself (e.g. if you changed the output format). Both approaches would work fine.

**Comment by phildawes** [comment]
@shougo: I agree, maybe even more so with vim than emacs. 
The reason I brought it up for emacs is that there seem to be multiple people who are active in contributing so a good likelihood that somebody will be interested in maintaining emacs support.

@marvelm: #racer irc sounds awesome! (and something I hadn't considered). Unfortunately I wouldn't have the spare time to man it, provide support etc. If others could then that would be ace, but I'd want to be confident we could do this before announcing #racer as a place to get support. 

@damieng: Sounds good to me. I used company because it was the first one I could get working when I originally tried to do emacs completion. 

@wilfred: Thanks for the complement, that means a lot to me. The thing that bothers me is that I'm not very good at replying to emacs and vim issues, PRs etc.., so people's issues go un-checked for days, sometimes a week or more. At the moment I'm more concerned about this than about protocol evolution (since this already exists for other external racer plugins, e.g. atom and sublime).

I think I'll try and create a separate project for emacs this weekend with a separate README etc, invite you all as collaborators and see how it goes.

**Comment by Shougo** [comment]
> The thing that bothers me is that I'm not very good at replying to emacs and vim issues, PRs etc.., so people's issues go un-checked for days, sometimes a week or more. 

OK.  I will check Vim issues in racer.

**Comment by bruno-medeiros** [comment]
> I think I'll try and create a separate project for emacs this weekend with a separate README etc, invite you all as collaborators and see how it goes.

That might be welcome for other reasons as well: I subscribe to Racer issues, and I hope that in the future I might contribute to Racer itself as well, when I have more time for that. However, I have no interest in Emacs integration (or Vim), so if that aspect is moved to a separate repository, it will cleanup up things a bit and reduce noise.

**Comment by phildawes** [comment]
I've setup an emacs-racer project here: https://github.com/racer-rust/emacs-racer and linked to it from the Racer README.md. How does melpa get updated? Does it just require a PR to https://github.com/milkypostman/melpa/tree/master/recipes ?

**Comment by ane** [comment]
Yes, that's how it works. There's a racer module there now (
https://github.com/milkypostman/melpa/blob/master/recipes/racer) so you
just need to change the address of that via a PR.

**Comment by fbergroth** [comment]
@phildawes yes, update the recipe to
```el
(racer :fetcher github
       :repo "racer-rust/emacs-racer")
```
and update the URL header in `racer.el`.

**Comment by Wilfred** [comment]
I think this issue can now be closed -- do you agree @phildawes?

**Comment by phildawes** [comment]
Yes, thanks v much everyone
