### ISSUE TITLE
Question: Do I need have to the rust source to get racer to work?

### ISSUE THREAD

**Issue by DontPanic345** [phildawes/racer#345]
Because I just downloaded and ran the Windows installer available from https://www.rust-lang.org/

**Comment by DontPanic345** [comment]
I found that you have already said yes in other some other issues that have since been closed, but how  about explicitly saying that you do need the source in the readme

**Comment by phildawes** [comment]
That's a fair point, thanks, I'll do that.

(Back when I originally wrote the README the only way to get rust was from
the source, so it was kindof assumed that you had the source on your
machine)

**Comment by bruno-medeiros** [comment]
Note that there is this Rust issue for having the source included in the main Rust distribution: https://github.com/rust-lang/rust/issues/19535
