### ISSUE TITLE
racer doesn't discover variables inside llvm_sys files

### ISSUE THREAD

**Issue by Wilfred** [phildawes/racer#346]
Completion works in this case:

```rust
extern crate llvm_sys;

use llvm_sys::
```

However, it doesn't work here:

```rust
extern crate llvm_sys;

use llvm_sys::core::
```

**Comment by phildawes** [comment]
Hi @Wilfred. I think this is because all the functions in llvm_sys::core:: are extern "C", and racer doesn't support extern yet. 
@varding opened #347 with the same problem. I will try and get this functionality added soon

**Comment by Wilfred** [comment]
Aha, that looks like the issue. Should I close this issue in favour of #347?

**Comment by phildawes** [comment]
Yeah, that would be good thanks. If after I've fixed that this still
doesn't work then reopen.

Thanks!
