### ISSUE TITLE
company: duplicated information in completion menu

### ISSUE THREAD

**Issue by birkenfeld** [phildawes/racer#353]
Since the merge of #350, when `company-tooltip-align-annotations` is nil, the element names and annotations are smashed against each other without any spacing. Also, the old annotation of "Type : Signature" was better than the new "Signature : Type".

Finally, this is not new, but the whole function signature is *very* long to display in the menu. I would suggest to

* remove the element name from the annotation as this is just duplicated information
* truncate after a certain length

cc @fbergroth 

![shot1](https://cloud.githubusercontent.com/assets/144359/9447208/76ace7e6-4a96-11e5-8ee1-43e3dc8bac6e.png)
![shot2](https://cloud.githubusercontent.com/assets/144359/9447209/76b058cc-4a96-11e5-9c8a-f2411f8023e6.png)

**Comment by fbergroth** [comment]
I agree, it's ugly with `company-tooltip-align-annotations` set to `nil`.

Trimming off the name is a good idea. With trimming, wouldn't it look better to have the completions outlined as "Signature : Type", like:
```
ConstantFloat (String, FloatWidth) : EnumVariant
ConstantInt (u64, LitIntType) : EnumVariant
```
Then it almost matches the actual signatures.

I'm just starting out with rust, so I might be missing some case.

**Comment by birkenfeld** [comment]
> With trimming, wouldn't it look better to have the completions outlined as "Signature : Type"

I agree.

**Comment by birkenfeld** [comment]
BTW, I also wondered why in the second screenshot some enum variants don't have a signature. I traced that to a bug in `s.el`:

https://github.com/magnars/s.el/pull/75

If that doesn't get fixed in due time, you might want to consider a workaround.

**Comment by birkenfeld** [comment]
ok nvm ;)

**Comment by fbergroth** [comment]
Nice catch :)
