### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by eriksvedang** [phildawes/racer#355]
Racer compiles fine on my system (OSX 10.10.5) but fails when I run it:

```
dyld: Library not loaded: x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libnative-4e7c5e5c.dylib
  Referenced from: /Users/erik/Projects/racer/bin//racer
  Reason: image not found
[1]    13080 trace trap  racer
```

**Comment by eriksvedang** [comment]
Turns out that ```cargo run``` works fine, it's just when I run it with ```racer``` that it fails. Any idea how I can work around this?

**Comment by ebfe** [comment]
> Referenced from: /Users/erik/Projects/racer/bin//racer

Are you sure you are not running an old binary? `cargo build` produces target/{debug,release}/racer.

**Comment by eriksvedang** [comment]
Thanks, that was it! That executable must have been there from a much earlier build.
