### ISSUE TITLE
Could not compile `syntex_syntax`

### ISSUE THREAD

**Issue by mikeyjcat** [phildawes/racer#388]
Am trying to build racer, got the message above. I have absolutely no clue how to resolve this, some pointers would be really appreciated.

Using a fresh rust 1.2 compiler, on Ubuntu 14.04, messages as follows:

mikehewitson1@ubuntu:~/racer$ cargo build --release --verbose
       Fresh typed-arena v1.0.1
       Fresh libc v0.1.10
       Fresh bitflags v0.3.2
       Fresh regex-syntax v0.2.1
       Fresh winapi v0.2.2
       Fresh rustc-serialize v0.3.16
       Fresh winapi-build v0.1.1
       Fresh unicode-xid v0.0.3
       Fresh memchr v0.1.5
       Fresh log v0.3.2
       Fresh toml v0.1.22
       Fresh aho-corasick v0.3.0
       Fresh regex v0.1.41
       Fresh kernel32-sys v0.1.4
   Compiling syntex_syntax v0.12.0
     Running `rustc /home/mikehewitson1/.cargo/registry/src/github.com-0a35038f75765ae4/syntex_syntax-0.12.0/src/lib.rs --crate-name syntex_syntax --crate-type lib -C opt-level=3 -g -C metadata=6381b52be90bb08f -C extra-filename=-6381b52be90bb08f --out-dir /home/mikehewitson1/racer/target/release/deps --emit=dep-info,link -L dependency=/home/mikehewitson1/racer/target/release/deps -L dependency=/home/mikehewitson1/racer/target/release/deps --extern libc=/home/mikehewitson1/racer/target/release/deps/liblibc-144c435538abd757.rlib --extern bitflags=/home/mikehewitson1/racer/target/release/deps/libbitflags-c495827ddcd6a202.rlib --extern rustc_serialize=/home/mikehewitson1/racer/target/release/deps/librustc_serialize-7ff5bfc027146194.rlib --extern unicode_xid=/home/mikehewitson1/racer/target/release/deps/libunicode_xid-162efc4f828d56d6.rlib --extern log=/home/mikehewitson1/racer/target/release/deps/liblog-f18a3e885170bd3f.rlib --extern term=/home/mikehewitson1/racer/target/release/deps/libterm-78a4699f433a04dc.rlib -Awarnings`
       Fresh env_logger v0.3.1
       Fresh term v0.2.11
Could not compile `syntex_syntax`.

**Comment by phildawes** [comment]
Hi Mike. Is this with racer 1.0 or with git master?

**Comment by mikeyjcat** [comment]
H Phil

cloned git repo

Oddly enough, i repeated the process on a  VM on my work laptop, and it worked.

**Comment by dirkraft** [comment]
I had the same problem. I am on mac and installed rust via `brew install rust` so I did a `brew update ; brew upgrade rust`. Then the `cargo build --release` completed without error after a few minutes.

It is day one with rust for me so I have no insight on why.

**Comment by dirkraft** [comment]
But then I had to `brew switch rust 1.1.0` backwards because bad cargo is in the homebrew rust 1.2.0 package: https://github.com/Homebrew/homebrew/issues/42992

**Comment by mikeyjcat** [comment]
I will try an update of rust tonight as well as another version and provide feedback.

**Comment by mikeyjcat** [comment]
The problem is resolved. Re-downloaded everything and rebuilt and its all working fine.
