### ISSUE TITLE
eldoc support? (or other argument assist)

### ISSUE THREAD

**Issue by dobkeratops** [phildawes/racer#40]
Would it be appropriate to drive 'eldoc' from racer ;
https://raw.githubusercontent.com/mooz/c-eldoc/master/images/screenshot.png

I see there's c-eldoc which in turn relies on cc-defs to generate function definitions

Even if it was imprecise (getting confused if the same method name is used differently in different traits) I think it would be better than nothing. (it could make some best guess if it can't resolve everything).

Another idea is the way that Xcode puts placeholders for arguments in the text, which it displays differently and its editing rules overwrite them

**Comment by Wilfred** [comment]
Working on a patch :)
