### ISSUE TITLE
show function signature in vim

### ISSUE THREAD

**Issue by syhkiller** [phildawes/racer#400]
<img width="326" alt="qq20150917-1 2x" src="https://cloud.githubusercontent.com/assets/2383723/9930491/a13b76ac-5d66-11e5-96de-8f2fcbebbf46.png">
how can i show the function signature in vim like the emacs. need some config in vimrc or should be a new enhance

**Comment by syhkiller** [comment]
i found it by myself!

**Comment by torpak** [comment]
how did you do it?

**Comment by KevinDetry** [comment]
let g:racer_experimental_completer = 1 in .vimrc
