### ISSUE TITLE
Cannot build Racer under Windows 10

### ISSUE THREAD

**Issue by ElfDecker** [phildawes/racer#402]
I am trying to build Racer for using it with eMacs, but when Cargo tries build kernel32-sys crate it finishes with an error:
![image](https://cloud.githubusercontent.com/assets/5684686/9960599/14d69dc2-5e24-11e5-8197-a85979249526.png)(Unable to run program due to absence of std-198068b3.dll. Try to reinstall program)
![image](https://cloud.githubusercontent.com/assets/5684686/9960621/4c5aba80-5e24-11e5-8fa3-f2b84af4600a.png)
What I need to do to fix it?

**Comment by phildawes** [comment]
Hi @ElfDecker 
I don't have windows, so I'm not sure. You could try deleting the Cargo.lock file and then doing a cargo clean, then rebuilding. This will cause the latest versions of packages to be loaded.

Which version of rust are you using?

**Comment by jaxx** [comment]
I have Win10 and I don't have any problems with building racer. If deleting Cargo.lock file doesn't help, then try do delete cargo crates cache. I had some problems with that too.

**Comment by rhoot** [comment]
This is happening to me as well. Using the stable 1.3 version of Rust, and current master of racer (b9750c373a).

**Comment by ElfDecker** [comment]
@phildawes, I tried to delete Cargo.lock file but it didn't help. I am using last stable version of Rust.
@jaxx, I tried to delete also .cargo folder, but it didn't help.

**Comment by rhoot** [comment]
Oh, simple fix. For some reason, the rust `bin` folder was not in my `PATH` until after I rebooted my computer. Having that folder in the `PATH` fixes this.

Sorry for the false alarm.

**Comment by ElfDecker** [comment]
@rhoot It was also reason of my problem. Rust installer didn't add it. Thank you for help!
@phildawes you can close this issue, I think

**Comment by phildawes** [comment]
Thanks @ElfDecker, glad you resolved the problem
