### ISSUE TITLE
Completion in CMD doesn't work on Win10

### ISSUE THREAD

**Issue by ElfDecker** [phildawes/racer#403]
When I am trying to test Racer in CMD I have an error:
"RUST_SRC_PATH environment variable must be set to point to the src directory of a Rust checkout."
My RUST_SRC_PATH variable is setted to "C:\Coding\Rust-src\rustc-1.3.0-src\rustc-1.3.0\src", but it isn't working. What I need to do?

**Comment by fubar-coder** [comment]
Did you set the environment variable after opening your command shell? If that's the case, then closing and re-opening should help.

**Comment by ElfDecker** [comment]
@fubar-coder thank you! I forgot about it, but you helped me!
