### ISSUE TITLE
Returning type of struct fields

### ISSUE THREAD

**Issue by sga001** [phildawes/racer#414]
Would it be possible for racer to instead (or in addition to) returning "StructField", to return the actual type (e.g., u8) when outputting the field of a struct?

**Comment by phildawes** [comment]
Hi @sga001. That sounds like a straightforward update and a good idea. 
I'm afraid I'm a bit busy working on rustc integration at the moment so am unlikely to get to this soon. If you fancy having a go at this feel free!

**Comment by sga001** [comment]
My understanding is that all it would take would be to implement print methods for the core::Ty structure and then return the appropriate string in the nameres::search_struct_fields. Is this right? These methods would look similar to syntex's ast::Ty's printing methods. The only issue that I see is that you convert from ast::Ty to racer Ty, but this conversion is not necessarily one-to-one. My initial thinking was to convert back from core::Ty to ast::Ty and use syntex's print methods instead of writing my own. Any thoughts?

**Comment by phildawes** [comment]
That might work, though these field types may not be fully realized (e.g. TyPathSearch). 
The alternative would be to pull the type out of the source text and display that. What do you intend to use this for?

**Comment by sga001** [comment]
My intention is to improve vim-racer so that when you are doing autocomplete you can see the type of the struct field (which I find to be very helpful when programming).

**Comment by phildawes** [comment]
Cool! In the short term it might be easiest to just display the field type from the source text. Racer's type inference is likely to get an overhaul in the not too distant future to be closer integrated with rustc

**Comment by hobofan** [comment]
@phildawes: What is the status on the type inference?
I think I'll have a go at pulling the type directly from the source text.
