### ISSUE TITLE
Support cargo install

### ISSUE THREAD

**Issue by fenhl** [phildawes/racer#416]
It would be nice if the first two steps of the installation guide could be replaced by a simple `cargo install racer`. As far as I can tell, the only preparation that needs to be made for this is uploading a new version of racer to [crates.io](https://crates.io/).

**Comment by hunterboerner** [comment]
`cargo install --git https://github.com/phildawes/racer.git` worked for me.

**Comment by phildawes** [comment]
I should really get round to doing a cargo racer release now that install is available. Time is a bit tight at the moment, I'll try and get to this over the next couple of days.

**Comment by bruno-medeiros** [comment]
cargo install is not yet available on stable Rust though (1.4)

**Comment by leeopop** [comment]
Cargo install is now available on Rust 1.5 stable.
http://blog.rust-lang.org/2015/12/10/Rust-1.5.html

**Comment by stanonyime** [comment]
I'm getting error 
```
invalid url `'https://github.com/phildawes/racer.git'`: relative URL without a b
ase
```
Rust 1.5 stable, Windows 8

**Comment by bruno-medeiros** [comment]
@stanonyime seems like the single quotes are being included in the URL. If you're using a plain Windows shell, you'll need to remove those.

**Comment by stanonyime** [comment]
@bruno-medeiros Oh. That worked. Thanks!

**Comment by PhiLhoSoft** [comment]
Beside the issue #459, cargo install works. Should this issue be closed?

**Comment by phildawes** [comment]
Oh good point @PhiLhoSoft thanks
