### ISSUE TITLE
noob here: which is the  RUST_SRC_PATH

### ISSUE THREAD

**Issue by cocodrino** [phildawes/racer#421]
Hi, sorry if it's a bit noob question. I've installed rust using the script

```bash
$ curl -f -L https://static.rust-lang.org/rustup.sh -O
$ sh rustup.sh
```

as show [this](https://static.rust-lang.org/rustup.sh)

the racer doc says

```txt
Set the RUST_SRC_PATH env variable to point to the 'src' dir in the rust source installation

(e.g. % export RUST_SRC_PATH=/usr/local/src/rust/src )

```

but is not clear for me which route is this, because I've not any folder named rust inside that route /usr/local/src/ 

thanks!!

**Comment by Shougo** [comment]
@cocodrino You must download rust's source code and set $RUST_SRC_PATH to the path.
Rust does not have rust standard source code information.

**Comment by phildawes** [comment]
(source can be downloaded from the rust [download page](https://www.rust-lang.org/downloads.html)

**Comment by cakoose** [comment]
Another noob here.  That web page gives you the "rustc" source, which I thought was maybe the wrong source and spent some time looking for the "rust" source.  Turns out the "rustc" source _is_ what we want.  It would be nice to make that explicit in the docs.

**Comment by phildawes** [comment]
Hi @cakoose. I just hit the 'source' download button and you're right, it does say 'rustc' source. I guess it's called that to distinguish from the other rust components that come in the binary download (cargo).  Confusing though! I'll update the docs

**Comment by vaer-k** [comment]
Rather than manually downloading and placing the source, you can use `rustup component add rust-src` as documented here https://github.com/racer-rust/racer
