### ISSUE TITLE
Newer versions of racer seem broken, including v1.0.0 tag

### ISSUE THREAD

**Issue by bruno-medeiros** [phildawes/racer#424]
So, I had an old executable of racer, and it's working fine (I don't remember when I compiled it, nor which commit it was based on).

With a source like this:
```
struct Circle {
    x: f64, y: f64,
}

impl Circle {
	fn blah() {
	}
}

pub fn fooA() {
	f
}

fn fooB() {
	C
}
```

If I ask for completions after the "f", I get flate, fmt_macros, fooA, fooB. Invoking after "C", I get Circle, Clone, Copy. Seems good.

Now, if try to build racer from master, or from the v1.0.0 tag, it is broken. If I ask for completions after the "f", I get fooA, and the same happens if I request invocation after "C".

I'm on Windows, Rust 1.5.

**Comment by bruno-medeiros** [comment]
I get this when trying `cargo test`: https://gist.github.com/bruno-medeiros/50e7ed1072a5e4749cd8

**Comment by bruno-medeiros** [comment]
Out running `D:\devel\tools.Rust\racer\target\debug\racer.exe complete-with-snippet 11 2 D:\devel\DDT\_runtime\RustLearn\src\main.rs`
```
PREFIX 1,2,f
MATCH fooA;fooA();11;0;D:\devel\DDT\_runtime\RustLearn\src\main.rs;Function;pub fn fooA() {
thread 'searcher' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:365
stack backtrace:
   0:           0xd23e9e - sys::backtrace::write::hc36430303764c83cKDt
   1:           0xd20a82 - panicking::on_panic::hce465205a2d3b675Znx
   2:           0xce80be - sys_common::unwind::begin_unwind_inner::h86ac48978b875778fls
   3:           0xce8a2b - sys_common::unwind::begin_unwind_fmt::h56fb5c589ef34e3elks
   4:           0xd20122 - rust_begin_unwind
   5:           0xd464c8 - panicking::panic_fmt::h1ab03301f58b14cc4HJ
   6:           0xd3f780 - panicking::panic::hda39392fa9337393BGJ
   7:           0x401b47 - option::Option<T>::unwrap::h15228627077570492570
                        at ../src/libcore/macros.rs:20
   8:           0x401629 - match_with_snippet_fn::h103d1a0777890930vaa
                        at src/bin/main.rs:28
   9:           0x40c204 - run_the_complete_fn::had64c30b98ded3acUia
                        at src/bin/main.rs:134
  10:           0x40b7b3 - complete_by_line_coords::closure.18451
                        at src/bin/main.rs:89
  11:           0x40b72a - boxed::F.FnBox<A>::call_box::h1004985486585072394
                        at ../src/liballoc/boxed.rs:485
  12:           0x40b32d - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h12716165419637241386
                        at ../src/liballoc/boxed.rs:501
  13:           0x40af60 - thread::Builder::spawn_inner::closure.18414
                        at ../src/libstd\thread/mod.rs:280
  14:           0x40aefc - sys_common::unwind::try::try_fn::h1283574122044604175
                        at ../src/libstd\sys/common\unwind/mod.rs:164
  15:           0xd13fe3 - sys_common::unwind::try::inner_try::hdba5f5128b367b6dDhs
  16:           0x40ae5b - sys_common::unwind::try::h10706665117069827630
                        at ../src/libstd\sys/common\unwind/mod.rs:136
  17:           0x40acf2 - thread::Builder::spawn_inner::closure.18390
                        at ../src/libstd\thread/mod.rs:280
  18:           0x40b59e - boxed::F.FnBox<A>::call_box::h11418706541805008807
                        at ../src/liballoc/boxed.rs:485
  19:           0xd29bbd - sys::thread::Thread::new::thread_start::hff19ea65aae908a6qQw
  20:         0x772c5a4c - jemalloc_constructor
ERROR:racer: Search thread paniced: Any
END
```

**Comment by phildawes** [comment]
Thanks Bruno, I'll check this out

**Comment by bruno-medeiros** [comment]
BTW, this must be related to the Rust version. The working Racer binary that I compiled, was compiled with Rust 1.1 or Rust 1.2 (don't remember exactly)

**Comment by pmarcelll** [comment]
I tried to figure out the failing tests, my guess is this is caused by a concurrent file usage (these functions all generate and use a file called src2.rs), but I didn't have time to confirm it.

**Comment by Jonesey13** [comment]
Having the same problems here; using a version of racer compiled on Rust 1.3 works with later versions of Rust but trying to use a version of racer compiled by Rust 1.4 or (1.6 nightly) gives no completions.

**Comment by phildawes** [comment]
Are you all on windows? Racer is buliding ok on rust stable 1.4 on my ubuntu machine

**Comment by Jonesey13** [comment]
Yes I'm on Windows 10. Just to clarify racer does build without any errors however it cannot find any completions from the src directory.

**Comment by bruno-medeiros** [comment]
Taking on the suspicion of it being Windows related, I've found something interesting. If I have this:
```
struct Circle { x: f64, y: f64, }  impl Circle { fn blah() { } } pub fn fooA() { } f
```
and requestion completion after the "f", I get correct results [ flate, fmt_macros, fooA() ]. Same for "C" as a prefix. However if the "f" is on the second line, it doesn't work. Perhaps this is related to line terminators somehow, messing up offsets?

**Comment by phildawes** [comment]
So you mean this 
```
struct Circle { x: f64, y: f64, }  impl Circle { fn blah() { } } pub fn fooA() { }
f       <--- complete here
```
...doesn't work on windows?

**Comment by bruno-medeiros** [comment]
> @bruno-medeiros So you mean this
> 
> struct Circle { x: f64, y: f64, }  impl Circle { fn blah() { } } pub fn fooA() { }
> f       <--- complete here
> 
> ...doesn't work on windows?

Exactly. Neither does this:

```
// blah blah
pub fn fooA() { }  f<--- complete here
``` 
If I have the time, I might try to debug this and check it out. I'm still a newbie to Racer's internals though, any suggestions where to look first in the source code?

The tests seem to run fine, I guess due to @pmarcelll fix.

**Comment by bruno-medeiros** [comment]
> @bruno-medeiros So you mean this
> 
> struct Circle { x: f64, y: f64, }  impl Circle { fn blah() { } } pub fn fooA() { }
> f       <--- complete here
> 
> ...doesn't work on windows?

Exactly. Neither does this:

```
// blah blah
pub fn fooA() { }  f<--- complete here
``` 
If I have the time, I might try to debug this and check it out. I'm still a newbie to Racer's internals though, any suggestions where to look first in the source code?

The tests seem to run fine now, I guess due to @pmarcelll fix.
