### ISSUE TITLE
Daemon mode does not handle quoted arguments.

### ISSUE THREAD

**Issue by vadimcn** [phildawes/racer#442]
`racer find-definition 1 1 "path/to/file.rs"` works, but
`echo find-definition 1 1 "path/to/file.rs" | racer daemon` panicks because racer can't open `"path/to/file.rs"`

Which makes sense, since [split_whitespace()](https://github.com/phildawes/racer/blob/1e05ca6a4fb9a07a486f7d132963fe13b8788323/src/bin/main.rs#L205) doesn't handle quoted arguments.

**Comment by vadimcn** [comment]
I suppose we could implement shell-like command line parser, but that'll just add complexity on both ends of the interface.  I propose we simply choose a non-printable character for argument separator, e.g. `'\x01'`.  

The only concern would be existing clients that use this interface.  Personally, I know only of [RustyCode](https://github.com/saviorisdead/RustyCode), but there may be others.  For this reason, I propose that we leave `daemon

**Comment by Draivin** [comment]
Could also be done as an argument to the daemon command, specifying the kind of argument separator.

**Comment by vadimcn** [comment]
Fixed by  #445
