### ISSUE TITLE
Racer support for local crate completion?

### ISSUE THREAD

**Issue by norcalli** [phildawes/racer#447]
I don't know if racer supports completion for extern crates yet for per project, but that would be swell. I don't see anything in the documentation and trying completion in vim isn't working.

**Comment by phildawes** [comment]
Hi @norcalli. Can you give an example? Racer should be able to complete things in extern crates if your cargo.toml is setup, but you may be running into another issue

**Comment by norcalli** [comment]
I installed racer using `multirust run beta cargo install --git https://github.com/phildawes/racer.git`. I have `racer 1.0.0` installed. I cd to a directory with Cargo.toml with `hyper` dependency listed which has been compiled. I run `racer complete hyper::` and I get no output. My RUST_SRC_PATH is set to the `rustsrc/rust/src` path which points to the git clone of rust. I really am not sure what I'm doing wrong.

**Comment by phildawes** [comment]
Hi @norcalli. Hmm, this should work. Maybe there's something up with the cargo install bit. Can you paste post your Cargo.toml and src file please and I'll take a look. Thanks!

**Comment by phildawes** [comment]
It also could be a problem finding the cargo directory under multirust. Is the cargo directory in `~/.multirust/toolchains/beta/cargo/registry/` ?
(I'm assuming you're on unix for multirust - right?)

**Comment by norcalli** [comment]
Yes Mac OSX multirust. https://github.com/norcalli/mintrs is the project if you are curious. Yes the cargo directory exists under `~/.multirust/toolchains/nightly/cargo/registry/`. Is there a special setting I should set or is this assumed to be the default?

**Comment by norcalli** [comment]
Ok strangely enough for some reason it is working now, but only when I specify the linenum column and filename, but not when I supply the prefix by itself. Does racer take into account context automatically from where it is called?

**Comment by phildawes** [comment]
Are you using this in an editor or on the command line? If command line, can you paste the commands? Thanks

**Comment by norcalli** [comment]
I ran `racer complete hyper::` and nothing showed. Then I made a simple test file with only `hyper::` in it at `src/test.rs` and ran `racer complete-with-snippet 1 7 src/test.rs` and it works. In neovim, I have deoplete installed as well, and it doesn't seem to be able to pick up the completion for specifically cargo plugins, but running omnicomplete (which calls `RacerComplete`) works.

**Comment by norcalli** [comment]
I figured it out. When running racer in neovim, it was creating a temporary file, so racer wasn't able to figure out which directory it was based in and the completions didn't work. If I could pass an option to racer about where to search for a path, then that would be optimal. Additionally, if `racer complete hyper::` could work based off of the current working directory at least if not through a flag `--cwd` or something.

**Comment by phildawes** [comment]
Hi @norcalli.
racer takes an additional parameter to allow usage of temporary files - you can tell it where the file should be (so that it can work out the cwd and the filename), and then tell it the tmpfile you actually want to read from.

```
$ ./target/release/racer complete --help
racer-complete v1.0.0
performs completion and returns matches

USAGE:
	racer complete <fqn>
	racer complete <linenum> <charnum> <path> [substitute_file]
```

E.g.   `racer complete 25 5 /path/to/crateroot/file.rs  /tmp/tmpfile.rs`

Hope that makes sense
