### ISSUE TITLE
Error on cargo build (fedora 23)

### ISSUE THREAD

**Issue by mrmcq2u** [phildawes/racer#453]
[mrmcq2u@Huawei-HG658c-instalacion racer]$ cargo build --release --verbose
       Fresh ansi_term v0.7.1
   Compiling regex-syntax v0.2.2
     Running `rustc /home/mrmcq2u/.cargo/registry/src/github.com-0a35038f75765ae4/regex-syntax-0.2.2/src/lib.rs --crate-name regex_syntax --crate-type lib -C opt-level=3 -g -C metadata=6d9e9f3bd76497d4 -C extra-filename=-6d9e9f3bd76497d4 --out-dir /home/mrmcq2u/Apps/racer/target/release/deps --emit=dep-info,link -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps --cap-lints allow`
       Fresh bitflags v0.3.3
       Fresh winapi v0.2.5
       Fresh typed-arena v1.0.1
       Fresh strsim v0.4.0
   Compiling unicode-xid v0.0.3
     Running `rustc /home/mrmcq2u/.cargo/registry/src/github.com-0a35038f75765ae4/unicode-xid-0.0.3/src/lib.rs --crate-name unicode_xid --crate-type lib -C opt-level=3 -g --cfg feature=\"default\" -C metadata=162efc4f828d56d6 -C extra-filename=-162efc4f828d56d6 --out-dir /home/mrmcq2u/Apps/racer/target/release/deps --emit=dep-info,link -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps --cap-lints allow`
       Fresh vec_map v0.4.0
   Compiling rustc-serialize v0.3.16
     Running `rustc /home/mrmcq2u/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.16/src/lib.rs --crate-name rustc_serialize --crate-type lib -C opt-level=3 -g -C metadata=7ff5bfc027146194 -C extra-filename=-7ff5bfc027146194 --out-dir /home/mrmcq2u/Apps/racer/target/release/deps --emit=dep-info,link -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps --cap-lints allow`
       Fresh clap v1.5.4
       Fresh libc v0.2.4
       Fresh log v0.3.4
       Fresh memchr v0.1.7
       Fresh aho-corasick v0.4.0
   Compiling regex v0.1.44
     Running `rustc /home/mrmcq2u/.cargo/registry/src/github.com-0a35038f75765ae4/regex-0.1.44/src/lib.rs --crate-name regex --crate-type lib -C opt-level=3 -g -C metadata=14c7acbc4abf7a40 -C extra-filename=-14c7acbc4abf7a40 --out-dir /home/mrmcq2u/Apps/racer/target/release/deps --emit=dep-info,link -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps --extern aho_corasick=/home/mrmcq2u/Apps/racer/target/release/deps/libaho_corasick-399b4a6bb6d46cc8.rlib --extern memchr=/home/mrmcq2u/Apps/racer/target/release/deps/libmemchr-49395bf503c0fa9c.rlib --extern regex_syntax=/home/mrmcq2u/Apps/racer/target/release/deps/libregex_syntax-6d9e9f3bd76497d4.rlib --cap-lints allow`
   Compiling env_logger v0.3.2
     Running `rustc /home/mrmcq2u/.cargo/registry/src/github.com-0a35038f75765ae4/env_logger-0.3.2/src/lib.rs --crate-name env_logger --crate-type lib -C opt-level=3 -g -C metadata=d6d4f90527157295 -C extra-filename=-d6d4f90527157295 --out-dir /home/mrmcq2u/Apps/racer/target/release/deps --emit=dep-info,link -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps --extern log=/home/mrmcq2u/Apps/racer/target/release/deps/liblog-db195e915b7f1b50.rlib --extern regex=/home/mrmcq2u/Apps/racer/target/release/deps/libregex-14c7acbc4abf7a40.rlib --cap-lints allow`
       Fresh winapi-build v0.1.1
   Compiling kernel32-sys v0.2.1
     Running `rustc /home/mrmcq2u/.cargo/registry/src/github.com-0a35038f75765ae4/kernel32-sys-0.2.1/build.rs --crate-name build_script_build --crate-type bin -g --out-dir /home/mrmcq2u/Apps/racer/target/release/build/kernel32-sys-35c1a745c861d23a --emit=dep-info,link -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps --extern build=/home/mrmcq2u/Apps/racer/target/release/deps/libbuild-304afb6bdff23d72.rlib --cap-lints allow`
error: could not exec the linker `cc`: No such file or directory (os error 2)
Build failed, waiting for other jobs to finish...
Could not compile `kernel32-sys`.

Caused by:
  Process didn't exit successfully: `rustc /home/mrmcq2u/.cargo/registry/src/github.com-0a35038f75765ae4/kernel32-sys-0.2.1/build.rs --crate-name build_script_build --crate-type bin -g --out-dir /home/mrmcq2u/Apps/racer/target/release/build/kernel32-sys-35c1a745c861d23a --emit=dep-info,link -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps -L dependency=/home/mrmcq2u/Apps/racer/target/release/deps --extern build=/home/mrmcq2u/Apps/racer/target/release/deps/libbuild-304afb6bdff23d72.rlib --cap-lints allow` (exit code: 101)

**Comment by phildawes** [comment]
Hi @mrmcq2u, I'm not that familiar with fedora, but I guess you need to install the build tools (e.g. gcc etc) to get 'cc'

**Comment by JIghtuse** [comment]
Works for me.
@mrmcq2u, must likely you will need these packages: `gcc`, `gcc-c++`:

    # dnf install gcc gcc-c++

**Comment by mrmcq2u** [comment]
no longer an issue
