### ISSUE TITLE
Use `fst` to store tags

### ISSUE THREAD

**Issue by hauleth** [phildawes/racer#464]
It could be useful to store tags in some way that would allow fast index search. I think that @BurntSushi [`fst`](https://github.com/BurntSushi/fst) crate would good solution.

Additional pro is that would allow distributing pre-generated tagfiles with crates (or Rust itself) instead of providing source code.

**Comment by phildawes** [comment]
Cool, I hadn't seen fst's before, thanks for the link. In the short term I don't have any plans for generating additional caches information over what is in the rlib files, but performance might force this at some point.

**Comment by hauleth** [comment]
I do not mean cache for crates. I was considering it rather as a functionality to serve pre-compiled symbols database instead of forcing user to clone whole rust-lang/rust repo.
