### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by PhiLhoSoft** [phildawes/racer#470]
Two remarks on the front page README:

- If I am not mistaken, points 3, 4 and 5 of the **From sources** section should be actually outside of the section, ie. common to this one and to the cargo install section. In this case, the command should have no path. Alternatively, duplicate the points and adapt to the other section.
- The [Atom package](https://atom.io/packages/racer) should be mentioned with the other plugins. Perhaps there are others, too.

**Comment by phildawes** [comment]
Yes I think you're right. I'm a bit strapped for time at the moment - do you fancy making these changes as a PR?  
(feel free to say no if you're similarly busy!)

**Comment by PhiLhoSoft** [comment]
I think it is "no" for now, for the reason you guessed... GitHub makes PRs a bit too convoluted for quick fixes. But there is no urge.

**Comment by pandeiro** [comment]
I was also affected by this, but asked in #rust and was informed. However unfortunately I still get no output from racer, even after exporting `$RUST_SRC_PATH` and pointing it to a Github checkout of the same Rust version.

Would definitely appreciate crystal clear instructions in the README, including how to verify that `racer` was installed correctly at the command line.
