### ISSUE TITLE
The lib crate is invisible from other crates from the same package.

### ISSUE THREAD

**Issue by krdln** [phildawes/racer#471]
Let's say that we have package `foo` with the `src/lib.rs` containing:
```rust
pub struct Foo { x: i32; }
```

Now, we try to use autocompletion in `src/main.rs`:
```rust
extern crate foo;
use foo::F
```

It should complete to struct `Foo`, but it doesn't work – Racer behaves as it had no idea of the existence of the `foo` crate. The similar issue exists when editing `tests/lib.rs` and probably `examples/*.rs` too.

**Comment by jaxx** [comment]
Can you pcopyut your Cargo.toml contents here for this library?

**Comment by phildawes** [comment]
Hi @krdln

I believe this does work, but you need to have 
```
[lib]
name = "foo"
path = "src/lib.rs"
```
in your Cargo.toml for rust to recognise the lib.rs as a crate root
