### ISSUE TITLE
cargo install racer is still using syntex_syntax version 0.26.0 (most recent).

### ISSUE THREAD

**Issue by kyleragan** [phildawes/racer#473]
There was a commit 7 days ago to explicitly select version 0.24.0, but that change is not reflected in the "cargo install racer" workflow.

**Comment by phildawes** [comment]
Apologies @kyleragan, I'll try and get a release out tonight

**Comment by jaxx** [comment]
This can be fixed by removing tilde from the beginning of the version number.
Tilde requirements specify a minimal version with some updates:

```
~1.2.3 := >=1.2.3 <1.3.0
~1.2   := >=1.2.0 <1.3.0
~1     := >=1.0.0 <2.0.0
```

**Comment by pmarcelll** [comment]
@phildawes I sent a PR.
