### ISSUE TITLE
Segfault when completing

### ISSUE THREAD

**Issue by Wilfred** [phildawes/racer#480]
Given the file:

```rust
use quickcheck::quickcheck;

use quickcheck::TestResult;

fn foo() {
    let r = TestResult::
}
```

racer segfaults:

```
$ RUST_SRC_PATH=/home/wilfred/src/rustc-1.5.0/src ~/src/racer/target/release/racer complete 6 24 /tmp/racer_crash.rs
PREFIX 24,24,

thread 'searcher' has overflowed its stackSegmentation fault (core dumped)
```

This occurs on both release and debug builds.

**Comment by jwilm** [comment]
I've started looking into this in #479

**Comment by charlag** [comment]
Possible dublicate:
https://github.com/phildawes/racer/issues/354

**Comment by Wilfred** [comment]
Yeah, looks very similar to #354. Note that I have `use quickcheck::quickcheck`. similar to the example in #354. Sounds like a good workaround is avoiding `use foo::foo` for now.

**Comment by jwilm** [comment]
Closing this in favor of making #354 the canonical issue for this problem
