### ISSUE TITLE
Racer could autocomplete chained calls

### ISSUE THREAD

**Issue by charlag** [phildawes/racer#481]
Racer completes usual function calls like:

``` rust
use curl::http::handle()
```

(`handle()` will be autocompleted)
but doesn't analyze returned value:

``` rust
use curl::http::handle().post(uri, body)
```

(`post()` call won't be autocompleted)
It is advanced feature but it would be definitely useful.
edit: can be related to https://github.com/phildawes/racer/issues/443

**Comment by phildawes** [comment]
Hi @charlag. Thanks for the issue. Racer does attempt to do this, but its type inference is not super strong at the moment. I am hoping to integrate it with rustc to improve this (as per comment in #443). Is it ok if I close this?

**Comment by charlag** [comment]
@phildawes thanks for your hard work! You're free to close it.

**Comment by matthiasbeyer** [comment]
Nice to see this issue already posted. I wondered about the same thing.
