### ISSUE TITLE
Completion does not work with String.trim

### ISSUE THREAD

**Issue by doubleagent** [phildawes/racer#482]
Racer will respond with `truncate` but not `trim`.

https://www.dropbox.com/s/tk6j15yrjshkd2p/Screenshot%202016-01-19%2021.57.05.png?dl=0

**Comment by jaxx** [comment]
How does this example compile? String constructor does not have any parameters.

**Comment by doubleagent** [comment]
Interesting.  I'm pretty new to this so I could be doing something wrong.

Anyway, Racer didn't show 'trim' as a completion option when writing [this introductory program](https://doc.rust-lang.org/book/guessing-game.html).

LOC here

```rust
    let guess: u32 = guess.trim().parse()
        .expect("Please type a number!");
```

I've encountered a handful of other places where Racer didn't show certain completion options that "The Book" wanted me to use in these introductory programs.  Would it be helpful to submit more tickets, or list them here?

**Comment by jwilm** [comment]
@doubleagent You're welcome to file issues for specific cases or list them here. If you choose to list them here, maybe update the title accordingly. This will make it easy for us to add tests for the cases that don't currently work and make them work :). By the way, if you're trying to get completions on a separate line (eg `.expect` in your last snippet) and not seeing anything, that is a [known issue](https://github.com/phildawes/racer/pull/468).

**Comment by jaxx** [comment]
@jwilm Isn't trim() string slice function? I mean that racer is looking from string.rs file, but there's only functions for String. String slice functions that apply to String also is in str.rs file.

If it is so, then maybe related issue is https://github.com/phildawes/racer/issues/443

**Comment by phildawes** [comment]
Racer can't complete any &str functions at the moment it seems. The following doesn't work
```
    let s: &str;
    s.trim();
```
There's a hack in there to convert &str to &Str, which I guess shows racer's age. I'll open a new issue and have a go at fixing this up

**Comment by phildawes** [comment]
I added #489 and then pushed a patch to fix. I think this should work now, thanks @doubleagent for the issue
