### ISSUE TITLE
Racer does not autocomplete Option.map

### ISSUE THREAD

**Issue by davidbecher** [phildawes/racer#508]
I noticed that racer currently is not able to auto complete Option.map (as well as other functions like Option.unwrap_or_else). Maybe it does not know how to auto complete functions which itself take some kind of function (like FnOnce e.g.) as an argument in the function signature?

**Comment by bluss** [comment]
The Option methods that don't complete in racer 1.2.6 are precisely those that have a type parameter on the method, and a type parameter must have a trait bound. Option::and::<U> does complete (has no bound on U).

`str` on the other hand can complete some methods with type parameters and bounds. `str` uses only where clauses though, no bounds embedded in the declarations of type parameters.

**Comment by phildawes** [comment]
Have just pushed a patch which I hope fixes this
