### ISSUE TITLE
racer does not complete crate from cargo

### ISSUE THREAD

**Issue by vityafx** [phildawes/racer#549]
> $ RUST_BACKTRACE=1 CARGO_HOME=~/.cargo RUST_SRC_PATH=~/workspace/rust/src racer complete 15 12 ~/workspace/project/src/main.rs 
> PREFIX 12,12,
> ERROR:racer::cargo: ERROR!: Error { repr: Os { code: 2, message: "No such file or directory" } } /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/cargo.rs 478
> thread 'searcher' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:330
> stack backtrace:
>    1:     0x556447ac7390 - sys::backtrace::tracing::imp::write::h09d7a562cdce3ef9Xcv
>    2:     0x556447ac9c9b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
>    3:     0x556447ac9908 - panicking::default_handler::hf7fdb8082bcb0f80lSz
>    4:     0x556447ab9bfc - sys_common::unwind::begin_unwind_inner::hfa667eeafdcc5750g1t
>    5:     0x556447aba048 - sys_common::unwind::begin_unwind_fmt::h7ecf9e1791369861m0t
>    6:     0x556447ac6801 - rust_begin_unwind
>    7:     0x556447af293f - panicking::panic_fmt::h62b9bbe5858e3d52lcM
>    8:     0x556447af2c18 - panicking::panic::h682c238a92c8c0b0SaM
>    9:     0x5564478f1275 - cargo::get_package_name::h8b09ce53efc52af1j5h
>                         at src/libcore/macros.rs:21
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/cargo.rs:168
>   10:     0x5564478ef974 - cargo::find_src_via_lockfile::h0aa73cd9928126d0wKh
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/cargo.rs:80
>   11:     0x5564478d54a2 - cargo::get_crate_file::h9b775e52a115ceffzTi
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/cargo.rs:525
>   12:     0x5564478d4a26 - nameres::get_crate_file::h10c88442d11f107dHOe
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:497
>   13:     0x5564478e5013 - matchers::match_extern_crate::h0f1e73736ef15f6b0Rg
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/matchers.rs:257
>   14:     0x5564478d74b9 - matchers::match_types::h6e50131af276f306Ozg
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/matchers.rs:21
>   15:     0x5564478d6039 - nameres::run_matchers_on_blob::h8d559c66bd5e4b30Y3e
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:685
>   16:     0x5564478d3b21 - nameres::search_scope::h8996aa81493a012abUe
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:652
>   17:     0x5564478da839 - nameres::search_local_scopes::h850cfb2207472cf2i6e
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:740
>   18:     0x5564478d1041 - nameres::resolve_name::h247735865b9d7e9e8lf
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:880
>   19:     0x55644788bfc2 - nameres::resolve_path::h12d724a9256a2368Xvf
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:959
>   20:     0x55644788c31d - nameres::resolve_path::h12d724a9256a2368Xvf
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:986
>   21:     0x5564478e7dc8 - matchers::match_use::hb917ab7b35f101efaih
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/matchers.rs:557
>   22:     0x5564478d80d2 - matchers::match_types::h6e50131af276f306Ozg
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/matchers.rs:27
>   23:     0x5564478d6039 - nameres::run_matchers_on_blob::h8d559c66bd5e4b30Y3e
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:685
>   24:     0x5564478d3b21 - nameres::search_scope::h8996aa81493a012abUe
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:652
>   25:     0x5564478da839 - nameres::search_local_scopes::h850cfb2207472cf2i6e
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:740
>   26:     0x5564478d1041 - nameres::resolve_name::h247735865b9d7e9e8lf
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:880
>   27:     0x55644788bfc2 - nameres::resolve_path::h12d724a9256a2368Xvf
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:959
>   28:     0x55644788c31d - nameres::resolve_path::h12d724a9256a2368Xvf
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:986
>   29:     0x5564478a97b1 - nameres::resolve_path_with_str::h1a1bdec5de15e977Wcf
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/nameres.rs:817
>   30:     0x5564478a3c39 - ast::resolve_ast_path::h1f6a3e52ee2e66eavnc
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:353
>   31:     0x5564478a5de6 - ast::ExprTypeVisitor<'c, 's>.visit..Visitor<'v>::visit_expr::h32401bac71355021Qxc
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:449
>   32:     0x5564478a5bac - ast::ExprTypeVisitor<'c, 's>.visit..Visitor<'v>::visit_expr::h32401bac71355021Qxc
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:458
>   33:     0x5564478a61a1 - ast::ExprTypeVisitor<'c, 's>.visit..Visitor<'v>::visit_expr::h32401bac71355021Qxc
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:494
>   34:     0x5564478a8f5d - ast::LetTypeVisitor<'c, 's>.visit..Visitor<'v>::visit_local::_$u7b$$u7b$closure$u7d$$u7d$::closure.22247
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:307
>   35:     0x5564478a76f8 - ast::LetTypeVisitor<'c, 's>.visit..Visitor<'v>::visit_local::haf210047b7055d3bIec
>                         at src/libcore/option.rs:577
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:303
>   36:     0x5564478c6030 - ast::get_let_type::h0f4be88a31a062f9hhd
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/visit.rs:651
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/visit.rs:67
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/visit.rs:636
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:961
>   37:     0x5564478ac2fd - typeinf::get_type_of_match::hb439d0503f117197SKd
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/typeinf.rs:114
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/typeinf.rs:223
>   38:     0x5564478a5f1e - ast::ExprTypeVisitor<'c, 's>.visit..Visitor<'v>::visit_expr::h32401bac71355021Qxc
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:454
>                         at src/libcore/option.rs:577
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:449
>   39:     0x55644788cea5 - ast::get_type_of::heedf755a99123fa5ngd
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/visit.rs:638
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/ast.rs:947
>   40:     0x55644788a326 - core::complete_from_file::hbd2e5b87aef9dc9aJkb
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/racer/core.rs:666
>   41:     0x55644785003f - sys_common::unwind::try::try_fn::h5182435574947467362
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/bin/main.rs:157
>                         at /home/fx/.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.2.9/src/bin/main.rs:107
>                         at src/libstd/thread/mod.rs:278
>                         at src/libstd/sys/common/unwind/mod.rs:127
>   42:     0x556447ac678b - __rust_try
>   43:     0x556447ac43cd - sys_common::unwind::inner_try::h0f62a9ecde9fb065iYt
>   44:     0x556447850f25 - boxed::F.FnBox<A>::call_box::h17601177604489463479
>                         at src/libstd/sys/common/unwind/mod.rs:123
>                         at src/libstd/thread/mod.rs:278
>                         at src/liballoc/boxed.rs:541
>   45:     0x556447ac8819 - sys::thread::Thread::new::thread_start::h4ef8643c78035313FPy
>   46:     0x7feba6227473 - start_thread
>   47:     0x7feba5d5069c - clone
>   48:                0x0 - <unknown>
> ERROR:racer: Search thread paniced: Any
> END

The code is:
```
extern crate discord;

use std::env;
use discord::{Discord, State};
use discord::model::{Event, OnlineStatus};

pub fn main() {
    // log in to the API
    let discord = Discord::from_bot_token(&env::var("DISCORD_TOKEN").expect("Bad DISCORD_TOKEN")).expect("Login failed");

    // establish websocket and voice connection
    let (mut connection, ready) = discord.connect().expect("connect failed");
    println!("[Ready]");
    let mut state = State::new(ready);
    discord.
}

```

The code is okay and it is a part of [example](https://github.com/SpaceManiac/discord-rs/blob/master/examples/dj.rs) of [discord-rs](https://github.com/SpaceManiac/discord-rs) project.

**Comment by phildawes** [comment]
Hi @vityafx 
Thanks for opening this, I think it is fixed now (works on my machine), could you try again and reopen if not. Thanks!

**Comment by vityafx** [comment]
Hi @phildawes ! Do you mean I should build it from latest commit which is e5ffe9efc1d10d4a7d66944b4c0939b7c575530e because I see nothing new in releases/tags?

**Comment by phildawes** [comment]
Hi Victor. Yes, or via cargo install
