### ISSUE TITLE
Bracket stop completion in use

### ISSUE THREAD

**Issue by yodalee** [phildawes/racer#554]
I try racer completer with
`use core::ops::{Index, IndexMut};`
I found that bracket will stop completion. So I cannot complete Index and IndexMut automatically.
Any hint where can I fix this problem?

**Comment by jaxx** [comment]
Does not work for me in Windows

**Comment by yodalee** [comment]
Not sure these two issue is related or not. Since they use different function call. I think @jaxx you can open another issue
