### ISSUE TITLE
Not able to find some functions

### ISSUE THREAD

**Issue by hotpxl** [phildawes/racer#575]
I'm using Racer to complete `ssh2` crate. My source code looks like this.

```rust
extern crate ssh2;

use ssh2::Session;

fn main() {
    let tcp = TcpStream::connect("127.0.0.1:22").unwrap();
    let mut session = Session::new().unwrap();
    let mut channel = session.channel
}
```

I try to complete directly using `racer` command. I set up `CARGO_HOME` correctly. I hit `racer complete 8 36 <absolute_path_to_file>`(completing right at `session.channel`) and it gives back

```
PREFIX 30,36,channe
MATCH channel_direct_tcpip,380,11,/home/hotpxl/.cargo/registry/src/github.com-1ecc6299db9ec823/ssh2-0.2.12/src/session.rs,Function,pub fn channel_direct_tcpip(&self, host: &str, port: u16,
                                src: Option<(&str, u16)>)
                                -> Result<Channel, Error>
MATCH channel_forward_listen,401,11,/home/hotpxl/.cargo/registry/src/github.com-1ecc6299db9ec823/ssh2-0.2.12/src/session.rs,Function,pub fn channel_forward_listen(&self,
                                  remote_port: u16,
                                  host: Option<&str>,
                                  queue_maxsize: Option<u32>)
                                  -> Result<(Listener, u16), Error>
MATCH channel_open,483,11,/home/hotpxl/.cargo/registry/src/github.com-1ecc6299db9ec823/ssh2-0.2.12/src/session.rs,Function,pub fn channel_open(&self, channel_type: &str,
                        window_size: u32, packet_size: u32,
                        message: Option<&str>) -> Result<Channel, Error>
END
```

But if you go into the `session.rs` file from `ssh2` crate, there is [this other](https://github.com/alexcrichton/ssh2-rs/blob/master/src/session.rs#L362) function that Racer were not able to find. I wonder why it is not showing this function as a candidate.

**Comment by paholg** [comment]
Using racer 1.2.10 with Emacs, I get completions for all four functions:
 
![2016-07-27-001441-s](https://cloud.githubusercontent.com/assets/4908217/17166995/41c0ad3a-538f-11e6-8002-bad3b301e2f2.png)

**Comment by hotpxl** [comment]
On my side I'm using Racer 1.2.10 as well but it doesn't work. I have traced the bug back to PR #577 . Please take a look at the commit, it's not huge, and you'll get it instantly. PR #579 also encountered this issue.

In short, `first_param_is_self` skips the first generic if there is any. But if the first generic is in return type, it would skip the parameter list itself completely.

Thanks
