### ISSUE TITLE
MIR

### ISSUE THREAD

**Issue by ernestrc** [phildawes/racer#586]
MIR based translation has been merged into master, and should be soon in nightly.  Any plans on exploring how racer should take advantage of that?

https://github.com/rust-lang/rust/pull/34096

**Comment by jonas-schievink** [comment]
...how *could* it take advantage of that?

**Comment by bstrie** [comment]
MIR isn't intended to provide a stable public interface, so that puts a damper on most external tools looking to leverage it for anything.
