### ISSUE TITLE
Unable to Build from Source on Linux Mint 18

### ISSUE THREAD

**Issue by m-rossini** [phildawes/racer#599]
Environment:
=>Linux MT-Linux 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

=>Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah

=>cargo 0.12.0-nightly (6b98d1f 2016-07-04)
=>rustc 1.11.0 (9b21dcd6a 2016-08-15)

Cloned racer repository, moved to it and then:
>cargo build --release --verbose

Resulted in failure below:

       Fresh winapi v0.2.8
       Fresh winapi-build v0.1.1
       Fresh bitflags v0.5.0
       Fresh unicode-xid v0.0.3
       Fresh regex-syntax v0.3.4
       Fresh bitflags v0.7.0
       Fresh unicode-width v0.1.3
       Fresh libc v0.2.14
       Fresh rustc-serialize v0.3.19
   Compiling kernel32-sys v0.2.2
       Fresh ansi_term v0.8.0
       Fresh vec_map v0.6.0
       Fresh utf8-ranges v0.1.3
       Fresh typed-arena v1.2.0
       Fresh strsim v0.4.1
   Compiling memchr v0.1.11
   Compiling toml v0.1.30
     Running `rustc /home/marcos/.cargo/registry/src/github.com-1ecc6299db9ec823/kernel32-sys-0.2.2/build.rs --crate-name build_script_build --crate-type bin -C opt-level=3 -g --out-dir /media/marcos/projetos/DevProjects/racer-master/target/release/build/kernel32-sys-d6afa5bd3d7cfaef --emit=dep-info,link -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps --extern build=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/libbuild-493a7b0628804707.rlib --cap-lints allow`
       Fresh log v0.3.6
   Compiling term_size v0.1.0
     Running `rustc /home/marcos/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-0.1.11/src/lib.rs --crate-name memchr --crate-type lib -C opt-level=3 -g -C metadata=c555f740a543880f -C extra-filename=-c555f740a543880f --out-dir /media/marcos/projetos/DevProjects/racer-master/target/release/deps --emit=dep-info,link -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps --extern libc=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/liblibc-1f3392fe1afd1313.rlib --cap-lints allow`
     Running `rustc /home/marcos/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.1.30/src/lib.rs --crate-name toml --crate-type lib -C opt-level=3 -g --cfg feature=\"rustc-serialize\" --cfg feature=\"default\" -C metadata=1a75b37a708f335b -C extra-filename=-1a75b37a708f335b --out-dir /media/marcos/projetos/DevProjects/racer-master/target/release/deps --emit=dep-info,link -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps --extern rustc_serialize=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/librustc_serialize-3561541d79c18212.rlib --cap-lints allow`
     Running `rustc /home/marcos/.cargo/registry/src/github.com-1ecc6299db9ec823/term_size-0.1.0/src/lib.rs --crate-name term_size --crate-type lib -C opt-level=3 -g --cfg feature=\"default\" -C metadata=19002b3950ee8264 -C extra-filename=-19002b3950ee8264 --out-dir /media/marcos/projetos/DevProjects/racer-master/target/release/deps --emit=dep-info,link -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps --extern libc=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/liblibc-1f3392fe1afd1313.rlib --cap-lints allow`
   Compiling clap v2.10.0
     Running `rustc /home/marcos/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.10.0/src/lib.rs --crate-name clap --crate-type lib -C opt-level=3 -g --cfg feature=\"unicode-width\" --cfg feature=\"wrap_help\" --cfg feature=\"strsim\" --cfg feature=\"libc\" --cfg feature=\"suggestions\" --cfg feature=\"color\" --cfg feature=\"default\" --cfg feature=\"ansi_term\" --cfg feature=\"term_size\" -C metadata=57680d55282acf10 -C extra-filename=-57680d55282acf10 --out-dir /media/marcos/projetos/DevProjects/racer-master/target/release/deps --emit=dep-info,link -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps --extern ansi_term=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/libansi_term-7a5cfeb616239ed5.rlib --extern strsim=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/libstrsim-cb9b0c8013c1be6f.rlib --extern bitflags=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/libbitflags-0e272044714c8076.rlib --extern unicode_width=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/libunicode_width-bcfd50e6d35d16e0.rlib --extern term_size=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/libterm_size-19002b3950ee8264.rlib --extern libc=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/liblibc-1f3392fe1afd1313.rlib --extern vec_map=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/libvec_map-d843695eff67d492.rlib --cap-lints allow`
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/media/marcos/projetos/DevProjects/racer-master/target/release/build/kernel32-sys-d6afa5bd3d7cfaef/build_script_build.0.o" "-o" "/media/marcos/projetos/DevProjects/racer-master/target/release/build/kernel32-sys-d6afa5bd3d7cfaef/build_script_build" "-Wl,--gc-sections" "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/media/marcos/projetos/DevProjects/racer-master/target/release/deps" "-L" "/media/marcos/projetos/DevProjects/racer-master/target/release/deps" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/media/marcos/projetos/DevProjects/racer-master/target/release/deps/libbuild-493a7b0628804707.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-39b92f95.rlib" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-l" "compiler-rt"
note: /usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lutil
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `kernel32-sys`.

Caused by:
  Process didn't exit successfully: `rustc /home/marcos/.cargo/registry/src/github.com-1ecc6299db9ec823/kernel32-sys-0.2.2/build.rs --crate-name build_script_build --crate-type bin -C opt-level=3 -g --out-dir /media/marcos/projetos/DevProjects/racer-master/target/release/build/kernel32-sys-d6afa5bd3d7cfaef --emit=dep-info,link -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps -L dependency=/media/marcos/projetos/DevProjects/racer-master/target/release/deps --extern build=/media/marcos/projetos/DevProjects/racer-master/target/release/deps/libbuild-493a7b0628804707.rlib --cap-lints allow` (exit code: 101)

**Comment by pmarcelll** [comment]
https://www.reddit.com/r/rust/comments/2g85e4/link_errors_in_ubuntu_1404/

**Comment by m-rossini** [comment]
Solved! Thanks
