### ISSUE TITLE
Racer no longer supports multirust

### ISSUE THREAD

**Issue by jwilm** [phildawes/racer#608]
Support for multirust was removed back in May with commit 7455a4841e8c6d588a669329705fd8a42c230bea. Switching to _rustup.rs_ fixes the issue (no completions/definitions in third-party crates), but there's still a lot of people on multirust. We should either figure out how to support both rustup and multirust or at least make it clear that multirust isn't supported. This is likely the cause of most "third party crate completions not working" issues.

**Comment by pmarcelll** [comment]
Rustup hit 1.0, so I think multirust support can be removed.

**Comment by jwilm** [comment]
Agreed
