### ISSUE TITLE
Publish a new version to crates.io

### ISSUE THREAD

**Issue by petrochenkov** [phildawes/racer#611]
`rustup component add rust-src` + `cargo install racer` together would make user experience nearly perfect, but the published version of racer is pretty old unfortunately (May 25, 2016) and doesn't contain https://github.com/phildawes/racer/pull/598. @phildawes Could you update it?

**Comment by the-kenny** [comment]
Note that this is also important for people who want to package `racer` with linux distributions. Many distributions prefer stable releases or forbid packaging unreleased (pure git) releases entirely.

**Comment by CryZe** [comment]
I just compiled the master version and type info lookup now takes over 10 seconds instead of a fraction of a second. Something massively broke since 1.2.10.

**Comment by jwilm** [comment]
@CryZe can you give an example exhibiting that regression?

**Comment by Diggsey** [comment]
Rust source packages are now in stable rust so this would be a big improvement 😉

**Comment by casimir** [comment]
Is there still some blockers?

**Comment by pmarcelll** [comment]
A new version was published and autocomplete seems to work with the packaged source of `std`.

**Comment by petrochenkov** [comment]
Hooray!
