### ISSUE TITLE
Completion using path shouldn't show non-static methods

### ISSUE THREAD

**Issue by jwilm** [phildawes/racer#621]
[This issue](https://github.com/jwilm/racerd/issues/56) was filed on _racerd_, but this is actually a problem with _racer_.

**Comment by jwilm** [comment]
cc @phynalle

**Comment by yodalee** [comment]
I cannot reproduce the error. My completion result is identical to v0.1 mentions in the issue link.

**Comment by TedDriggs** [comment]
I'm pretty sure this is actually valid; see [Universal Function Call Syntax](https://doc.rust-lang.org/book/ufcs.html) in the book.

**Comment by jwilm** [comment]
Oh, totally. This is working as expected. I've been thinking this was the inverse problem for some reason. Thanks @TedDriggs
