### ISSUE TITLE
Using libraries in rust compiler?

### ISSUE THREAD

**Issue by hotpxl** [phildawes/racer#634]
I noticed that racer is doing lexing and parsing itself. And even after parsing into an AST, there are many parts that revert to character level cursor manipulation. It imposes heavy restrictions on the kind of grammar it can handle correctly (for example in rust spec whitespaces doesn't matter that much). I wonder if it is possible to use parts of librustc to parse and build the AST. I think the major concern is if librustc is able to handle incomplete source files.

**Comment by jonas-schievink** [comment]
This has been the plan for a long time. There's been much work on rustc to improve IDE integration, including things like handling source files with syntax errors. Sadly, rustc is still too slow to be invoked like racer: Some plugins will call racer on every keystroke. When incremental compilation is more mature (and more parts of the compiler are made incremental), this might eventually change. For that reason, IDE integration of rustc is kind of put on hold right now.

Your best bet might be to try contributing to rustc's incremental compilation. There are a few [mentored issues](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AE-mentor+label%3AA-incr-comp) you can try to tackle if you want.

**Comment by hotpxl** [comment]
Thanks for the quick response. I'll definitely see what I can do.
