### ISSUE TITLE
can not registry.

### ISSUE THREAD

**Issue by morganw** [phildawes/racer#635]
Hi,
E:\projects\Rust\racer>cargo build --release
Updating registry `https://github.com/rust-lang/crates.io-index`

when I want to build racer, this sentence "Updating registry `https://github.com/rust-lang/crates.io-index`" can not success, stop moving. my OS is win7. I do not know what's wrong happened.

**Comment by jwilm** [comment]
Can you build other rust projects?

**Comment by morganw** [comment]
this is my first use cargo to build, and now I use "cargo install racer " successful.

**Comment by jwilm** [comment]
It sounds like you're all set; can this issue be closed?

**Comment by morganw** [comment]
OK, thanks.
