### ISSUE TITLE
Debuginfo for release profile

### ISSUE THREAD

**Issue by drasolka** [phildawes/racer#637]
Is there some reason to have [`debug=true`](https://github.com/phildawes/racer/blob/master/Cargo.toml#L20) for release profile?

**Comment by bluss** [comment]
line numbers in backtraces for the default config that most users will use. That helps debugging and bug reports.

**Comment by jwilm** [comment]
There's not much info in [the commit message that added it](https://github.com/phildawes/racer/commit/c9e753b616fa202cd71a754b868557450b93ce4b). Agree with @bluss that it's helpful for bug reports.
