### ISSUE TITLE
non-std completes not working

### ISSUE THREAD

**Issue by vvuk** [phildawes/racer#647]
Configuration: windows, rustup, nightly rustc.  racer built from source, `RUST_SRC_PATH = c:/Users/vladimir/.multirust/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/src`

This works, everything from `racer/src/racer`:
```
$ RUST_LOG=trace ../../target/release/racer.exe complete std::io::B
DEBUG:racer::nameres: do_file_search std
DEBUG:racer::nameres: do_file_search srcpaths C:/Users/vladimir/.multirust/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/src
DEBUG:racer::nameres: do_file_search v is ["C:/Users/vladimir/.multirust/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/src", "."]
DEBUG:racer::nameres: do_external_search path ["io", "B"] "C:/Users/vladimir/.multirust/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/src\\libstd\\lib.rs"
DEBUG:racer::nameres: do_external_search path ["io"] "C:/Users/vladimir/.multirust/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/src\\libstd\\lib.rs"
...
```

This doesn't:
```
$ RUST_LOG=trace ../../target/release/racer.exe complete toml::V
DEBUG:racer::nameres: do_file_search toml
DEBUG:racer::nameres: do_file_search srcpaths C:/Users/vladimir/.multirust/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/src
DEBUG:racer::nameres: do_file_search v is ["C:/Users/vladimir/.multirust/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/src", "."]
```

As best I can tell, racer is only ever calling `do_file_search` (I don't see how it can ever get into, e.g. `nameres::resolve_name`, but I didn't follow things all the way through).

**Comment by jwilm** [comment]
Have you built the project at least once? Racer won't be able to get crate completions otherwise.

**Comment by vvuk** [comment]
Yep, I'm running the built version.  Behaves identically on Linux, with both nightly and stable rust.

**Comment by Powersource** [comment]
I managed to reproduce on Arch Linux:
```
me@pc[src/racer]% RUST_LOG=trace ../../target/release/racer complete std::io::B
DEBUG:racer::nameres: do_file_search std
DEBUG:racer::nameres: do_file_search srcpaths /usr/src/rust/src
DEBUG:racer::nameres: do_file_search v is ["/usr/src/rust/src", "."]
DEBUG:racer::nameres: do_external_search path ["io", "B"] "/usr/src/rust/src/libstd/lib.rs"
DEBUG:racer::nameres: do_external_search path ["io"] "/usr/src/rust/src/libstd/lib.rs"
etc...
me@pc[src/racer]% RUST_LOG=trace ../../target/release/racer complete toml::V   
DEBUG:racer::nameres: do_file_search toml
DEBUG:racer::nameres: do_file_search srcpaths /usr/src/rust/src
DEBUG:racer::nameres: do_file_search v is ["/usr/src/rust/src", "."]
me@pc[src/racer]% 
```
I also get the same results when swapping the path to the racer installed by my package manager, v. 1.2.10-1.

A weird thing is, in vscode I can type e.g. iron::B and BeforeMiddleware pops up, i.e. module (or whatever it's called) completion seems to work. Other completions don't seem to work, e.g. typing IronError in the code can be completed but using its ::new() doesn't pop anything up. I can't reproduce this in the terminal, even the one embedded in vscode :S

**Comment by jwilm** [comment]
I think this is the same as #551. It's starting to look like a bug with the `complete` subcommand on the command line.
