### ISSUE TITLE
Racer does not autocomplete functions with lifetime parameters

### ISSUE THREAD

**Issue by TedDriggs** [phildawes/racer#652]
In the code sample below, placing the cursor at the marked point will suggest the field and method called `catalog`, but won't suggest `validate` as a method. Removing the lifetime parameter completely will cause the method to appear, and adding it back causes it to disappear from the suggestions again.

```rust
pub struct Anvil<C: Catalog> {
    catalog: C,
}

impl<C: Catalog> Anvil<C> {
    
    /// Creates a new validator with the specified metric and function catalog.
    pub fn new(catalog: C) -> Self {
        Anvil { catalog: catalog }
    }
    
    pub fn catalog(&self) -> &C {
        &self.catalog
    }
    
    pub fn validate<'i>(&self, expr: &'i Expression) -> AnvilResult<'i> {
        use ::ast::Expression::*;
        match *expr {
            Constant(_) => Ok(ExprReturnType::Constant),
            Interval(_) => Ok(ExprReturnType::Interval),
            Metric(ref m) => self.metric(m),
            Function(ref fc) => self.function(fc),
            Binary(ref op) => self.binary(op),
        }
    }

    pub fn example(&self) {
        &self. // AUTOCOMPLETE HERE
    }
```

**Comment by andjo403** [comment]
I can not reproduce this fault on the latest commit on master

**Comment by TedDriggs** [comment]
I just ran `cargo install racer --force` and I'm still seeing a repro of this.

**Comment by jwilm** [comment]
@TedDriggs the latest racer hasn't been published to crates.io, yet. I'm not saying it's fixed, just that you and @andjo403 are running different versions.

**Comment by pmarcelll** [comment]
@TedDriggs a new version was published, can you try this again?

**Comment by TedDriggs** [comment]
This now works; thanks for the fix!
