### ISSUE TITLE
Changelog has not changed in almost a year

### ISSUE THREAD

**Issue by AaronFriel** [phildawes/racer#653]
I'm curious what the state of the project is, I see commit made and issues resolved, but I don't see any changes logged.

**Comment by jwilm** [comment]
Hey, sorry about that! Thanks for reminding us! I'll make an effort to update it in the future - especially for the pending 2.0 publication. Given my own time constraints, I probably won't try to fill in the changelog for stuff that's already been released, but you or someone else is welcome to do so. Either way, I will make an effort to update the log for new changes going forward.

**Comment by AaronFriel** [comment]
Thank you!
