### ISSUE TITLE
racer cannot find definition when importing module with self

### ISSUE THREAD

**Issue by tspiteri** [phildawes/racer#663]
Racer can find the definition of `io::Read` when importing with `use std::io;`, but not when importing with `use std::io::self`.

**Comment by sinkuu** [comment]
#665

**Comment by jwilm** [comment]
Seems to work now 
![image](https://cloud.githubusercontent.com/assets/4285147/21467422/b52d4836-c9ba-11e6-9572-8fc15bb2d3e2.png)

**Comment by tspiteri** [comment]
It works for the case that matters, thanks! As a nit, it works for `use std::io::{self};` but not for `use std::io::self;`. Of course it makes no sense to `use std::io::self;`.
