### ISSUE TITLE
How to update from version 1.2.10 to 2.0.4 using cargo?

### ISSUE THREAD

**Issue by magj2006** [phildawes/racer#679]
How to update from version 1.2.10 to 2.0.4 using cargo? 

There is an error when I run cargo (0.15.0-nightly) install racer due to I installed it a month ago.

 Downloading racer v2.0.4
error: binary `racer` already exists in destination as part of `racer v1.2.10`

**Comment by golddranks** [comment]
Run `carco install --force racer`

**Comment by magj2006** [comment]
Thank you very much!
