### ISSUE TITLE
Can not install on Windows 7, SSL error

### ISSUE THREAD

**Issue by drazde** [phildawes/racer#688]
When I try to install with cargo
``cargo install racer``

I have this error:
``    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading racer v2.0.5
error: [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - Il server di revoca � offline. La funzione richiamata non � in grado di completare il controllo di revoca.)``

NB1: I have install ssl cert with IExplorer
NB2: The same error if I try to compile from source

S.O.: Windows 7

**Comment by r10o** [comment]
Looks like an issue with curl itself:

https://curl.haxx.se/mail/lib-2016-03/0202.html

**Comment by drazde** [comment]
Sorry, but I'm a newbie!
Where could put the CURLOPT_SSL_OPTIONS flag? Is there a cargo config file where i put curl options?

**Comment by drazde** [comment]
It is a problem of cargo not is a problem of racer
