### ISSUE TITLE
Adding cargo projects to RUST_SRC_PATH?

### ISSUE THREAD

**Issue by rsw0x** [phildawes/racer#73]
Is there a recommended way of going about this? I did some poking around and saw that racer looks for lib.rs in name/lib.rs or libname/lib.rs, but not every project adheres to the same file layout so racer doesn't always pick them up(e.g, [Glutin](https://github.com/tomaka/glutin) )

**Comment by eklavya** [comment]
I did some experimentation with Cargo and was able to get source roots, however when I set RUST_SRC_PATH to concatenation of those roots, it didn't work for racer. It erred out with 

```Company: Back-end racer-company-complete error "/Users/eklavya/Documents/racer/target/release/racer exited with status 101" with args (candidates )```

Maybe I did something wrong.

**Comment by phildawes** [comment]
I added some support for cargo dependencies into Racer. This is only tested on my ubuntu box - I guess it should work on mac but I'm not sure about windows. If anybody tests on these OSes could they report back here please? - Thanks!

**Comment by phildawes** [comment]
I believe the new cargo support fixes this issue, closing!

**Comment by johnjelinek** [comment]
@phildawes: how does cargo support fix this issue? Example: I imported `glium` as a dependency to my rust project. `racer complete glium::DisplayBuild` doesn't return anything. Am I missing a step to add it?

**Comment by johnjelinek** [comment]
hmm ... but my editor started pulling in some of the crates, it found them in `$HOME/.cargo/registry/src` -- I wonder why I can't access them via `racer complete`

**Comment by dleslie** [comment]
Likewise, I don't seem to be seeing any completion for packages installed via cargo.

**Comment by jwilm** [comment]
@dleslie which version of Racer are you using and are you using multirust?

**Comment by dleslie** [comment]
```
$ racer -V
racer 1.2.10
$ rustc -V
rustc 1.12.0 (3191fbae9 2016-09-23)
$ cargo -V
cargo 0.13.0-nightly (109cb7c 2016-08-19)
```

No multirust. :)
