### ISSUE TITLE
Have a "complete" without resorting to temporary file

### ISSUE THREAD

**Issue by alkama** [phildawes/racer#90]
This is just a suggestion and might very well be stupid, but I feel it could be awesome to spare some HDD/SSD lifetime:

Would it be possible to request a contextual ```complete``` (with ```linenum``` and ```charnum```) but passing what is currently a temporary file (```fname```) as standard input instead?

Another great enhancement could be to daemonize racer, maybe by having it detach a server component on first launch, then following calls would be simple clients hitting on that server like what gocode does. It might enable caching, even faster response time, and concur into releasing some IO stress on HDD ?

**Comment by untitaker** [comment]
`/tmp` should be in RAM on most systems, FWIW:

**Comment by danielkza** [comment]
A workaround on Unix platforms is passing `/dev/sdtin` as an input file.

**Comment by alkama** [comment]
Hum, It's probably not doable, since racer seems to use that temp files location (path) to search for cargo declared dependancies and have a project context too.
Lets close the issue :)

**Comment by danielkza** [comment]
It's absolutely doable, it would just take a bit of refactoring so the file name is passed as a parameter to the relevant functions.
